<script lang="ts">
	import BotMessageSquare from '@lucide/svelte/icons/bot-message-square';
	import type { Snippet } from 'svelte';

	interface Props {
		children: Snippet;
		class?: string;
	}

	let { children, class: className = '' }: Props = $props();
</script>

<div
	class="border-primary bg-primary/10 flex flex-col gap-2.5 rounded-lg border-l-8 px-6 py-4 {className}"
>
	{@render children()}
	<div class="flex items-end justify-end gap-2.5">
		<BotMessageSquare class="text-primary h-5 w-5" />
		<span class="text-primary text-sm">This is generated by LLM.</span>
	</div>
</div>
