<script lang="ts">
	import type { PageProps } from './$types';
	import type { ReportComment } from '$lib/types/report';
	import { Badge } from '$lib/components/ui/badge';
	import StatementCard from '$lib/components/report/StatementCard.svelte';
	import BeeswarmChart from '$lib/components/report/BeeswarmChart.svelte';
	import ReportSection from '$lib/components/report/ReportSection.svelte';
	import AiCallout from '$lib/components/report/AiCallout.svelte';
	import ReportNav from '$lib/components/report/ReportNav.svelte';
	import Down from '@lucide/svelte/icons/download';
	import {
		getEngagementStats,
		getConsensusStatements,
		getDivisiveStatements,
		getSignificantComments
	} from '$lib/types/report';
	import { Button } from '$lib/components/ui/button';

	let { data }: PageProps = $props();

	const stats = $derived(getEngagementStats(data.reportData));
	const consensusStatements = $derived(getConsensusStatements(data.reportData, 5));
	const divisiveStatements = $derived(getDivisiveStatements(data.reportData, 5));
	const significantComments = $derived(getSignificantComments(data.reportData));
	const totalParticipants = $derived(data.reportData.participants.length);

	let selectedTid = $state<number | null>(null);

	const activeComment = $derived.by(() => {
		const tid = selectedTid ?? null;
		if (tid == null) return null;
		return significantComments.find((c) => c.tid === tid) ?? null;
	});

	function handleHoverComment(comment: ReportComment | null) {
		if (comment) selectedTid = comment.tid;
	}

	let engagementOpen = $state(true);
	let agreementOpen = $state(true);
	let differencesOpen = $state(true);
	let groupsOpen = $state(true);
	let deeperLookOpen = $state(true);
</script>

{#snippet numberedStatements(statements: ReportComment[])}
	<div class="flex flex-col gap-6">
		{#each statements as comment, i (comment.tid)}
			<div class="flex items-start gap-6">
				<span class="text-xl font-semibold text-gray-400/50">#{i + 1}</span>
				<div class="flex-1">
					<StatementCard {comment} groups={data.reportData.groups} {totalParticipants} />
				</div>
			</div>
		{/each}
	</div>
{/snippet}

{#snippet statCard(label: string, value: string | number)}
	<div
		class="bg-card ring-border h-44 w-72 content-center items-center rounded-xl p-6 text-center shadow-[0px_2px_4px_0px_rgba(0,0,0,0.10)] ring-1"
	>
		<p class="text-card-foreground text-3xl leading-9 font-semibold">{value}</p>
		<p class="text-muted-foreground mt-1.5 text-lg leading-7 font-semibold">{label}</p>
	</div>
{/snippet}

<ReportNav />
<div class="flex flex-col items-center overflow-hidden py-20">
	<!-- Header -->
	<header
		id="dive-in"
		class="bg-card mb-16 flex w-full max-w-[1200px] flex-col items-center gap-4 rounded-xl px-24 py-12 text-center"
	>
		<Badge
			class="bg-primary/10 text-muted-foreground rounded-3xl px-4 py-2 text-lg font-semibold"
		>
			Interim Report
		</Badge>
		<h1 class="text-foreground text-5xl leading-[52px] font-bold">
			South Staffordshire Local Plan
		</h1>
		<p class="report-body">
			This conversation was run by
			<span class="text-primary">South Staffordshire</span>. The topic was
			<span class="text-primary">Shaping South Staffordshire</span>
		</p>

		<div class="text-card-foreground mt-6 w-full text-left text-3xl leading-8 font-semibold">
			General summary
		</div>
		<AiCallout class="w-full max-w-4xl text-left">
			<p class="report-body font-normal">
				Group description will be generated by LLM analysis.
			</p>
		</AiCallout>
	</header>

	<!-- Engagement at a glance -->
	<ReportSection
		id="engagement"
		title="Engagement at a glance"
		subtitle="What was the process?"
		bind:open={engagementOpen}
	>
		<div class="max-w-4xl pt-2 pb-6">
			<p class="report-body">
				This engagement took participants into a journey of three steps:<br />
			</p>
			<ol class="report-body list-inside list-decimal pt-1 pl-1">
				<li>learn</li>
				<li>survey</li>
				<li>interactive survey</li>
			</ol>
			<br />
			<p class="report-body">Here is a breakdown of what happened:</p>
		</div>

		<div class="-mx-24 flex flex-wrap items-center justify-center gap-10 px-4">
			{@render statCard(
				'Participants have taken part',
				stats.totalParticipants.toLocaleString()
			)}
			{@render statCard('People grouped', stats.totalStatements.toLocaleString())}
			{@render statCard('Votes cast', stats.totalVotes.toLocaleString())}
			{@render statCard('Statements submitted', stats.totalStatements.toLocaleString())}
			{@render statCard(
				'Votes per participants on average',
				(stats.totalVotes / Math.max(stats.totalParticipants, 1)).toFixed(2)
			)}
			{@render statCard('Opinion groups were formed', stats.totalGroups.toString())}
		</div>

		<p class="report-subheading mt-6">How did we recruit the participants?</p>
		<p class="report-body">
			The participants were recruited through multiple channels. They receive a draw at the
			end.
		</p>
	</ReportSection>

	<!-- Areas of Agreement -->
	<ReportSection id="agreement" title="Areas of agreement" bind:open={agreementOpen}>
		<div class="max-w-4xl pt-2 pb-6">
			<p class="report-body">
				There is a great deal of agreement across the conversation. These areas are special
				because these are the ideas that are agreed across opinion groups despite other
				different views they might be holding.
			</p>
		</div>

		<p class="report-subheading">What do people agree on?</p>

		<AiCallout>
			<p class="report-body">Group description will be generated by LLM analysis.</p>
		</AiCallout>

		<p class="report-body">
			List of statements ({consensusStatements.length}) of where there is agreement:
		</p>

		{@render numberedStatements(consensusStatements)}
	</ReportSection>

	<!-- Where there are differences -->
	<ReportSection title="Where there are differences" bind:open={differencesOpen}>
		<div class="max-w-4xl pt-2 pb-6">
			<p class="report-body">
				These statements show the most significant differences between opinion groups. They
				highlight where participants disagree most strongly.
			</p>
		</div>

		{@render numberedStatements(divisiveStatements)}
	</ReportSection>

	<!-- Emerging opinion groups -->
	<ReportSection id="groups" title="Emerging opinion groups" bind:open={groupsOpen}>
		<p class="report-body">
			There are {data.reportData.groups.length} groups emerging after 2 weeks in the engagement...
		</p>

		<p class="report-subheading">What are the groups like?</p>

		{#each data.reportData.groups as group (group.group_id)}
			{@const label = String.fromCharCode(65 + group.group_id)}
			{@const repComments = group.representative_comments
				.map((rc) => data.reportData.comments.find((c) => c.tid === rc.tid))
				.filter((c) => c != null)}

			<h3 class="text-foreground text-3xl leading-9 font-semibold">
				Group {label} ({group.members.length} participants)
			</h3>

			<AiCallout class="w-full max-w-[960px]">
				<p class="report-body">Group description will be generated by LLM analysis.</p>
			</AiCallout>

			<p class="report-body">Statements which make this group unique, by their votes:</p>

			{#each repComments as comment (comment.tid)}
				<StatementCard {comment} groups={data.reportData.groups} {totalParticipants} />
			{/each}
		{/each}
	</ReportSection>

	<!-- Taking a deeper look — Beeswarm -->
	<ReportSection
		title="Taking a deeper look at the results"
		subtitle="How were the statements perceived? Do they bridge groups together, or do they move groups apart?"
		bind:open={deeperLookOpen}
		id="deep-dive"
	>
		<div class="max-w-4xl pt-2 pb-6">
			<p class="report-body">
				Hover over or click on a dot to see the statement. Dots on the left represent
				consensus statement that has higher level bridging strength; dots on the right
				represent divisive statement that has lower level bridging strength.
			</p>
		</div>

		<div class="overflow-x-auto">
			<BeeswarmChart
				comments={significantComments}
				height={240}
				dotRadius={5}
				{selectedTid}
				onHoverComment={handleHoverComment}
			/>
		</div>

		{#if activeComment}
			<StatementCard
				comment={activeComment}
				groups={data.reportData.groups}
				{totalParticipants}
			/>
		{/if}
	</ReportSection>
</div>
