[workspace]
members = [
    "api", "comhairle_macros","adaptors/heyform-rust-sdk", "adaptors/ragflow", "api_spec_gen"]
resolver="2"

[workspace.package]
rust-version = "1.95"

[workspace.dependencies]
aide = "0.14.0"
async-trait = "0.1.83"
lettre = "0.11.16"
minijinja = "2.10.2"
serde = "1.0.218"
serde_json = "1.0.139"
sqlx = "0.8.3"
tokio = "1.43.0"
uuid = "1.14.0"
