[package]
name = "sensemakar_workers"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
sensemakar_jobs= {path='../sensemakar_jobs'}
tokio = { version = "1.53.1", features = ["full"] }
serde = { version = "1.0.229", features = ["serde_derive"] }
sensemakar= {path='../sensemakar_core'}
sensemakar_types= {path='../sensemakar_types'}
rig = "0.42.0"
rig-core = "0.42.0"
apalis = { version = "0.7.4", features = ["uuid","limit"] }
apalis-redis = "0.7.4"
