use std::sync::Arc;

use aide::axum::{
    routing::{delete_with, get_with, post_with, put_with},
    ApiRouter,
};
use axum::{
    extract::{Json, Path, State},
    http::StatusCode,
};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::{
    error::ComhairleError,
    models::translations::{
        self, CreateTextContent, CreateTextTranslation, TextContent, TextContentId,
        TextTranslation, UpdateTextContent, UpdateTextTranslation,
    },
    ComhairleState,
};

use super::auth::RequiredAdminUser;

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct TextContentWithTranslations {
    #[serde(flatten)]
    pub text_content: TextContent,
    pub translations: Vec<TextTranslation>,
}

#[derive(Deserialize, JsonSchema)]
pub struct CreateTextContentRequest {
    pub primary_locale: String,
    pub format: translations::TextFormat,
}

/// Get a TextContent with all its translations
async fn get_text_content_with_translations(
    State(state): State<Arc<ComhairleState>>,
    Path(text_content_id): Path<Uuid>,
    RequiredAdminUser(_user): RequiredAdminUser,
) -> Result<(StatusCode, Json<TextContentWithTranslations>), ComhairleError> {
    let text_content_id = TextContentId::from(text_content_id);

    let text_content = translations::get_text_content_by_id(&state.db, &text_content_id).await?;
    let translations =
        translations::get_text_translations_by_content_id(&state.db, &text_content_id).await?;

    Ok((
        StatusCode::OK,
        Json(TextContentWithTranslations {
            text_content,
            translations,
        }),
    ))
}

/// Create new TextContent
async fn create_text_content(
    State(state): State<Arc<ComhairleState>>,
    RequiredAdminUser(_user): RequiredAdminUser,
    Json(request): Json<CreateTextContentRequest>,
) -> Result<(StatusCode, Json<TextContent>), ComhairleError> {
    let create_content = CreateTextContent {
        primary_locale: request.primary_locale,
        format: request.format,
    };

    let text_content = translations::create_text_content(&state.db, &create_content).await?;

    Ok((StatusCode::CREATED, Json(text_content)))
}

/// Update TextContent
async fn update_text_content(
    State(state): State<Arc<ComhairleState>>,
    Path(text_content_id): Path<Uuid>,
    RequiredAdminUser(_user): RequiredAdminUser,
    Json(update): Json<UpdateTextContent>,
) -> Result<(StatusCode, Json<TextContent>), ComhairleError> {
    let text_content_id = TextContentId::from(text_content_id);
    let text_content =
        translations::update_text_content(&state.db, &text_content_id, &update).await?;

    Ok((StatusCode::OK, Json(text_content)))
}

/// Delete TextContent and all its translations
async fn delete_text_content(
    State(state): State<Arc<ComhairleState>>,
    Path(text_content_id): Path<Uuid>,
    RequiredAdminUser(_user): RequiredAdminUser,
) -> Result<(StatusCode, Json<TextContent>), ComhairleError> {
    let text_content_id = TextContentId::from(text_content_id);
    let text_content = translations::delete_text_content(&state.db, &text_content_id).await?;

    Ok((StatusCode::OK, Json(text_content)))
}

/// Get a specific translation for a TextContent and locale
async fn get_text_translation(
    State(state): State<Arc<ComhairleState>>,
    Path((text_content_id, locale)): Path<(Uuid, String)>,
    RequiredAdminUser(_user): RequiredAdminUser,
) -> Result<(StatusCode, Json<TextTranslation>), ComhairleError> {
    let text_content_id = TextContentId::from(text_content_id);
    let translation = translations::get_text_translation_by_content_and_locale(
        &state.db,
        &text_content_id,
        &locale,
    )
    .await?;

    Ok((StatusCode::OK, Json(translation)))
}

#[derive(Serialize, Deserialize, JsonSchema, Debug)]
pub struct CreateOrUpdateTextTranslationRequest {
    pub content: String,
    /// Whether this translation was generated by AI (defaults to false)
    pub ai_generated: Option<bool>,
    /// Whether this translation requires human validation (defaults to false)
    pub requires_validation: Option<bool>,
}

/// Create or update a translation for a specific TextContent and locale
async fn create_or_update_text_translation(
    State(state): State<Arc<ComhairleState>>,
    Path((text_content_id, locale)): Path<(Uuid, String)>,
    RequiredAdminUser(_user): RequiredAdminUser,
    Json(request): Json<CreateOrUpdateTextTranslationRequest>,
) -> Result<(StatusCode, Json<TextTranslation>), ComhairleError> {
    let text_content_id = TextContentId::from(text_content_id);

    // Check if translation already exists
    match translations::get_text_translation_by_content_and_locale(
        &state.db,
        &text_content_id,
        &locale,
    )
    .await
    {
        Ok(existing_translation) => {
            // Update existing translation
            let update = UpdateTextTranslation {
                locale: Some(locale),
                content: Some(request.content),
                ai_generated: request.ai_generated,
                requires_validation: request.requires_validation,
                ..Default::default()
            };
            let updated_translation =
                translations::update_text_translation(&state.db, &existing_translation.id, &update)
                    .await?;
            Ok((StatusCode::OK, Json(updated_translation)))
        }
        Err(_) => {
            // Create new translation
            let create_request = CreateTextTranslation {
                content_id: text_content_id,
                locale,
                content: request.content,
                ai_generated: request.ai_generated,
                requires_validation: request.requires_validation,
            };
            let translation =
                translations::create_text_translation(&state.db, &create_request).await?;
            Ok((StatusCode::CREATED, Json(translation)))
        }
    }
}

/// Update a specific translation
async fn update_text_translation(
    State(state): State<Arc<ComhairleState>>,
    Path((text_content_id, locale)): Path<(Uuid, String)>,
    RequiredAdminUser(_user): RequiredAdminUser,
    Json(update): Json<UpdateTextTranslation>,
) -> Result<(StatusCode, Json<TextTranslation>), ComhairleError> {
    let text_content_id = TextContentId::from(text_content_id);

    // First get the existing translation to get its ID
    let existing_translation = translations::get_text_translation_by_content_and_locale(
        &state.db,
        &text_content_id,
        &locale,
    )
    .await?;

    let updated_translation =
        translations::update_text_translation(&state.db, &existing_translation.id, &update).await?;

    Ok((StatusCode::OK, Json(updated_translation)))
}

// Automatically translate a specific translation
async fn auto_translate(
    State(state): State<Arc<ComhairleState>>,
    Path((_, translation_id)): Path<(TextContentId, Uuid)>,
    RequiredAdminUser(_user): RequiredAdminUser,
) -> Result<(StatusCode, Json<TextTranslation>), ComhairleError> {
    let new_translation = translations::auto_generate_translation(
        &state.db,
        &state.translation_service,
        &translation_id,
    )
    .await?;
    Ok((StatusCode::OK, Json(new_translation)))
}

// Automatically translate all languages for this text content
async fn auto_translate_all(
    State(state): State<Arc<ComhairleState>>,
    Path(text_content_id): Path<TextContentId>,
    RequiredAdminUser(_user): RequiredAdminUser,
) -> Result<(StatusCode, Json<TextContentWithTranslations>), ComhairleError> {
    let text_content = translations::get_text_content_by_id(&state.db, &text_content_id).await?;
    let translations = translations::auto_generate_all_translations(
        &state.db,
        &state.translation_service,
        &text_content_id,
    )
    .await?;
    let result = TextContentWithTranslations {
        text_content,
        translations,
    };
    Ok((StatusCode::OK, Json(result)))
}

/// Delete a specific translation
async fn delete_text_translation(
    State(state): State<Arc<ComhairleState>>,
    Path((text_content_id, locale)): Path<(Uuid, String)>,
    RequiredAdminUser(_user): RequiredAdminUser,
) -> Result<(StatusCode, Json<TextTranslation>), ComhairleError> {
    let text_content_id = TextContentId::from(text_content_id);

    // First get the existing translation to get its ID
    let existing_translation = translations::get_text_translation_by_content_and_locale(
        &state.db,
        &text_content_id,
        &locale,
    )
    .await?;

    let deleted_translation =
        translations::delete_text_translation(&state.db, &existing_translation.id).await?;

    Ok((StatusCode::OK, Json(deleted_translation)))
}

pub fn router(state: Arc<ComhairleState>) -> ApiRouter {
    ApiRouter::new()
        // TextContent routes
        .api_route(
            "/",
            post_with(create_text_content, |op| {
                op.id("CreateTextContent")
                    .tag("Translations")
                    .summary("Create new TextContent")
                    .description("Create a new TextContent entry that can hold translations")
                    .response::<201, Json<TextContent>>()
            }),
        )
        .api_route(
            "/{text_content_id}",
            get_with(get_text_content_with_translations, |op| {
                op.id("GetTextContentWithTranslations")
                    .tag("Translations")
                    .summary("Get TextContent with all translations")
                    .description("Get a TextContent entry with all its translations")
                    .response::<200, Json<TextContentWithTranslations>>()
            }),
        )
        .api_route(
            "/{text_content_id}",
            put_with(update_text_content, |op| {
                op.id("UpdateTextContent")
                    .tag("Translations")
                    .summary("Update TextContent")
                    .description("Update a TextContent entry")
                    .response::<200, Json<TextContent>>()
            }),
        )
        .api_route(
            "/{text_content_id}",
            delete_with(delete_text_content, |op| {
                op.id("DeleteTextContent")
                    .tag("Translations")
                    .summary("Delete TextContent")
                    .description("Delete a TextContent entry and all its translations")
                    .response::<200, Json<TextContent>>()
            }),
        )
        // TextTranslation routes
        .api_route(
            "/{text_content_id}/{locale}",
            get_with(get_text_translation, |op| {
                op.id("GetTextTranslation")
                    .tag("Translations")
                    .summary("Get translation for specific locale")
                    .description("Get a translation for a specific TextContent and locale")
                    .response::<200, Json<TextTranslation>>()
            }),
        )
        .api_route(
            "/{text_content_id}/{locale}",
            post_with(create_or_update_text_translation, |op| {
                op.id("CreateOrUpdateTextTranslation")
                    .tag("Translations")
                    .summary("Create or update translation")
                    .description(
                        "Create a new translation or update existing one for a specific locale",
                    )
                    .response::<200, Json<TextTranslation>>()
                    .response::<201, Json<TextTranslation>>()
            }),
        )
        .api_route(
            "/{text_content_id}/{locale}",
            put_with(update_text_translation, |op| {
                op.id("UpdateTextTranslation")
                    .tag("Translations")
                    .summary("Update translation")
                    .description("Update an existing translation for a specific locale")
                    .response::<200, Json<TextTranslation>>()
            }),
        )
        .api_route(
            "/{text_content_id}/{locale}",
            delete_with(delete_text_translation, |op| {
                op.id("DeleteTextTranslation")
                    .tag("Translations")
                    .summary("Delete translation")
                    .description("Delete a translation for a specific locale")
                    .response::<200, Json<TextTranslation>>()
            }),
        )
        .api_route(
            "/{text_content_id}/translate",
            post_with(auto_translate_all, |op| {
                op.id("GenerateAllTranslations")
                    .tag("Translations")
                    .summary("Generate all translations for this Text Content")
                    .description("Use the default locale content as the reference text and generate automatic translations for each language form it")
                    .response::<200, Json<TextContentWithTranslations>>()
            }),
        )
        .api_route(
            "/{text_content_id}/{locale}/translate",
            post_with(auto_translate_all, |op| {
                op.id("AutomaticallyGenerateTranslation")
                    .tag("Translations")
                    .summary("Automatically generate this language")
                    .description("Use the primary_locale language and translate this language from it using the tarnslation service")
                    .response::<200, Json<TextTranslation>>()
            }),
        )
        .with_state(state)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        models::translations::TextFormat,
        setup_server,
        test_helpers::{test_state, UserSession},
    };
    use axum::http::StatusCode;
    use serde_json::json;
    use std::{error::Error, sync::Arc};

    #[sqlx::test]
    async fn test_create_text_content(pool: sqlx::PgPool) -> Result<(), Box<dyn Error>> {
        let state = test_state().db(pool).call()?;
        let app = setup_server(Arc::new(state)).await?;

        let mut admin_session = UserSession::new_admin();
        admin_session.signup(&app).await?;

        // Create TextContent
        let create_request = json!({
            "primary_locale": "en",
            "format": "plain"
        });

        let (status, response, _) = admin_session
            .post(&app, "/translations", create_request.to_string().into())
            .await?;

        assert_eq!(status, StatusCode::CREATED);
        let text_content: TextContent = serde_json::from_value(response)?;
        assert_eq!(text_content.primary_locale, "en");
        assert_eq!(text_content.format, TextFormat::Plain);

        Ok(())
    }

    #[sqlx::test]
    async fn test_get_text_content_with_translations(
        pool: sqlx::PgPool,
    ) -> Result<(), Box<dyn Error>> {
        let state = test_state().db(pool).call()?;
        let app = setup_server(Arc::new(state)).await?;

        let mut admin_session = UserSession::new_admin();
        admin_session.signup(&app).await?;

        // Create TextContent
        let create_request = json!({
            "primary_locale": "en",
            "format": "rich"
        });

        let (status, response, _) = admin_session
            .post(&app, "/translations", create_request.to_string().into())
            .await?;

        let text_content: TextContent = serde_json::from_value(response)?;

        // Add a translation
        let translation_request = json!({
            "content_id": text_content.id,
            "content": "Hello World",
            "ai_generated": false,
            "requires_validation": false
        });

        admin_session
            .post(
                &app,
                &format!("/translations/{}/en", text_content.id),
                translation_request.to_string().into(),
            )
            .await?;

        // Get TextContent with translations
        let (status, response, _) = admin_session
            .get(&app, &format!("/translations/{}", text_content.id))
            .await?;

        assert_eq!(status, StatusCode::OK);

        let result: TextContentWithTranslations = serde_json::from_value(response)?;
        assert_eq!(result.text_content.id, text_content.id);
        assert_eq!(result.translations.len(), 1);
        assert_eq!(result.translations[0].content, "Hello World");
        assert_eq!(result.translations[0].locale, "en");

        Ok(())
    }

    #[sqlx::test]
    async fn test_update_text_content(pool: sqlx::PgPool) -> Result<(), Box<dyn Error>> {
        let state = test_state().db(pool).call()?;
        let app = setup_server(Arc::new(state)).await?;

        let mut admin_session = UserSession::new_admin();
        admin_session.signup(&app).await?;

        // Create TextContent
        let create_request = json!({
            "primary_locale": "en",
            "format": "plain"
        });

        let (_, response, _) = admin_session
            .post(&app, "/translations", create_request.to_string().into())
            .await?;

        let text_content: TextContent = serde_json::from_value(response)?;

        // Update TextContent
        let update_request = json!({
            "primary_locale": "es",
            "format": "rich"
        });

        let (status, response, _) = admin_session
            .put(
                &app,
                &format!("/translations/{}", text_content.id),
                update_request.to_string().into(),
            )
            .await?;

        assert_eq!(status, StatusCode::OK);

        let updated_content: TextContent = serde_json::from_value(response)?;
        assert_eq!(updated_content.primary_locale, "es");
        assert_eq!(updated_content.format, TextFormat::Rich);

        Ok(())
    }

    #[sqlx::test]
    async fn test_delete_text_content(pool: sqlx::PgPool) -> Result<(), Box<dyn Error>> {
        let state = test_state().db(pool).call()?;
        let app = setup_server(Arc::new(state)).await?;

        let mut admin_session = UserSession::new_admin();
        admin_session.signup(&app).await?;

        // Create TextContent
        let create_request = json!({
            "primary_locale": "en",
            "format": "plain"
        });

        let (status, response, _) = admin_session
            .post(&app, "/translations", create_request.to_string().into())
            .await?;

        let text_content: TextContent = serde_json::from_value(response)?;

        // Delete TextContent
        let (status, response, _) = admin_session
            .delete(&app, &format!("/translations/{}", text_content.id))
            .await?;

        assert_eq!(status, StatusCode::OK);

        let deleted_content: TextContent = serde_json::from_value(response)?;
        assert_eq!(deleted_content.id, text_content.id);

        // Verify it's deleted
        let (status, response, _) = admin_session
            .get(&app, &format!("/translations/{}", text_content.id))
            .await?;

        assert_eq!(status, StatusCode::NOT_FOUND);

        Ok(())
    }

    #[sqlx::test]
    async fn test_create_text_translation(pool: sqlx::PgPool) -> Result<(), Box<dyn Error>> {
        let state = test_state().db(pool).call()?;
        let app = setup_server(Arc::new(state)).await?;

        let mut admin_session = UserSession::new_admin();
        admin_session.signup(&app).await?;

        // Create TextContent first
        let create_request = json!({
            "primary_locale": "en",
            "format": "plain"
        });

        let (status, response, _) = admin_session
            .post(&app, "/translations", create_request.to_string().into())
            .await?;

        let text_content: TextContent = serde_json::from_value(response)?;

        // Create translation
        let translation_request = json!({
            "content": "Hola Mundo",
            "ai_generated": true,
            "requires_validation": true
        });

        let (status, response, _) = admin_session
            .post(
                &app,
                &format!("/translations/{}/es", text_content.id),
                translation_request.to_string().into(),
            )
            .await?;

        assert_eq!(status, StatusCode::CREATED);

        let translation: TextTranslation = serde_json::from_value(response)?;
        assert_eq!(translation.content, "Hola Mundo");
        assert_eq!(translation.locale, "es");
        assert_eq!(translation.ai_generated, true);
        assert_eq!(translation.requires_validation, true);

        Ok(())
    }

    #[sqlx::test]
    async fn test_get_text_translation(pool: sqlx::PgPool) -> Result<(), Box<dyn Error>> {
        let state = test_state().db(pool).call()?;
        let app = setup_server(Arc::new(state)).await?;

        let mut admin_session = UserSession::new_admin();
        admin_session.signup(&app).await?;

        // Create TextContent and translation
        let create_request = json!({
            "primary_locale": "en",
            "format": "plain"
        });

        let (status, response, _) = admin_session
            .post(&app, "/translations", create_request.to_string().into())
            .await?;

        let text_content: TextContent = serde_json::from_value(response)?;

        let translation_request = json!({
            "content": "Bonjour le monde",
            "ai_generated": false,
            "requires_validation": false
        });

        admin_session
            .post(
                &app,
                &format!("/translations/{}/fr", text_content.id),
                translation_request.to_string().into(),
            )
            .await?;

        // Get specific translation
        let (status, response, _) = admin_session
            .get(&app, &format!("/translations/{}/fr", text_content.id))
            .await?;

        assert_eq!(status, StatusCode::OK);

        let translation: TextTranslation = serde_json::from_value(response)?;
        assert_eq!(translation.content, "Bonjour le monde");
        assert_eq!(translation.locale, "fr");

        Ok(())
    }

    #[sqlx::test]
    async fn test_update_existing_translation_via_post(
        pool: sqlx::PgPool,
    ) -> Result<(), Box<dyn Error>> {
        let state = test_state().db(pool).call()?;
        let app = setup_server(Arc::new(state)).await?;

        let mut admin_session = UserSession::new_admin();
        admin_session.signup(&app).await?;

        // Create TextContent and translation
        let create_request = json!({
            "primary_locale": "en",
            "format": "plain"
        });

        let (status, response, _) = admin_session
            .post(&app, "/translations", create_request.to_string().into())
            .await?;

        let text_content: TextContent = serde_json::from_value(response)?;

        // Create initial translation
        let initial_translation = json!({
            "content": "Original text",
            "ai_generated": false,
            "requires_validation": false
        });

        admin_session
            .post(
                &app,
                &format!("/translations/{}/de", text_content.id),
                initial_translation.to_string().into(),
            )
            .await?;

        // Update via POST (should update existing)
        let updated_translation = json!({
            "content": "Updated text",
            "ai_generated": true,
            "requires_validation": true
        });

        let (status, response, _) = admin_session
            .post(
                &app,
                &format!("/translations/{}/de", text_content.id),
                updated_translation.to_string().into(),
            )
            .await?;

        assert_eq!(status, StatusCode::OK);

        let translation: TextTranslation = serde_json::from_value(response)?;
        assert_eq!(translation.content, "Updated text");
        assert_eq!(translation.ai_generated, true);
        assert_eq!(translation.requires_validation, true);

        Ok(())
    }

    #[sqlx::test]
    async fn test_update_text_translation_via_put(
        pool: sqlx::PgPool,
    ) -> Result<(), Box<dyn Error>> {
        let state = test_state().db(pool).call()?;
        let app = setup_server(Arc::new(state)).await?;

        let mut admin_session = UserSession::new_admin();
        admin_session.signup(&app).await?;

        // Create TextContent and translation
        let create_request = json!({
            "primary_locale": "en",
            "format": "plain"
        });

        let (status, response, _) = admin_session
            .post(&app, "/translations", create_request.to_string().into())
            .await?;

        let text_content: TextContent = serde_json::from_value(response)?;

        // Create initial translation
        let initial_translation = json!({
            "content": "Original text",
            "ai_generated": false,
            "requires_validation": false
        });

        admin_session
            .post(
                &app,
                &format!("/translations/{}/it", text_content.id),
                initial_translation.to_string().into(),
            )
            .await?;

        // Update via PUT
        let update_request = json!({
            "content": "Testo aggiornato",
            "ai_generated": true
        });

        let (status, response, _) = admin_session
            .put(
                &app,
                &format!("/translations/{}/it", text_content.id),
                update_request.to_string().into(),
            )
            .await?;

        assert_eq!(status, StatusCode::OK);

        let translation: TextTranslation = serde_json::from_value(response)?;
        assert_eq!(translation.content, "Testo aggiornato");
        assert_eq!(translation.ai_generated, true);
        // requires_validation should remain unchanged
        assert_eq!(translation.requires_validation, false);

        Ok(())
    }

    #[sqlx::test]
    async fn test_delete_text_translation(pool: sqlx::PgPool) -> Result<(), Box<dyn Error>> {
        let state = test_state().db(pool).call()?;
        let app = setup_server(Arc::new(state)).await?;

        let mut admin_session = UserSession::new_admin();
        admin_session.signup(&app).await?;

        // Create TextContent and translation
        let create_request = json!({
            "primary_locale": "en",
            "format": "plain"
        });

        let (status, response, _) = admin_session
            .post(&app, "/translations", create_request.to_string().into())
            .await?;

        let text_content: TextContent = serde_json::from_value(response)?;

        let translation_request = json!({
            "content": "Text to delete",
            "ai_generated": false,
            "requires_validation": false
        });

        admin_session
            .post(
                &app,
                &format!("/translations/{}/pt", text_content.id),
                translation_request.to_string().into(),
            )
            .await?;

        // Delete translation
        let (status, response, _) = admin_session
            .delete(&app, &format!("/translations/{}/pt", text_content.id))
            .await?;

        assert_eq!(status, StatusCode::OK);

        let deleted_translation: TextTranslation = serde_json::from_value(response)?;
        assert_eq!(deleted_translation.content, "Text to delete");

        // Verify it's deleted
        let (status, response, _) = admin_session
            .get(&app, &format!("/translations/{}/pt", text_content.id))
            .await?;

        assert_eq!(status, StatusCode::NOT_FOUND);

        Ok(())
    }

    #[sqlx::test]
    async fn test_non_admin_access_denied(pool: sqlx::PgPool) -> Result<(), Box<dyn Error>> {
        let state = test_state().db(pool).call()?;
        let app = setup_server(Arc::new(state)).await?;

        let mut regular_session = UserSession::new("user", "password", "user@example.com");
        regular_session.signup(&app).await?;

        // Try to create TextContent as regular user
        let create_request = json!({
            "primary_locale": "en",
            "format": "plain"
        });

        let (status, response, _) = regular_session
            .post(&app, "/translations", create_request.to_string().into())
            .await?;

        // Should be forbidden or unauthorized
        assert!(status == StatusCode::UNAUTHORIZED || status == StatusCode::FORBIDDEN);

        Ok(())
    }

    #[sqlx::test]
    async fn test_get_nonexistent_text_content(pool: sqlx::PgPool) -> Result<(), Box<dyn Error>> {
        let state = test_state().db(pool).call()?;
        let app = setup_server(Arc::new(state)).await?;

        let mut admin_session = UserSession::new_admin();
        admin_session.signup(&app).await?;

        let fake_uuid = uuid::Uuid::new_v4();
        let (status, response, _) = admin_session
            .get(&app, &format!("/translations/{}", fake_uuid))
            .await?;

        assert_eq!(status, StatusCode::NOT_FOUND);

        Ok(())
    }

    #[sqlx::test]
    async fn test_get_nonexistent_translation(pool: sqlx::PgPool) -> Result<(), Box<dyn Error>> {
        let state = test_state().db(pool).call()?;
        let app = setup_server(Arc::new(state)).await?;

        let mut admin_session = UserSession::new_admin();
        admin_session.signup(&app).await?;

        // Create TextContent but no translation
        let create_request = json!({
            "primary_locale": "en",
            "format": "plain"
        });

        let (status, response, _) = admin_session
            .post(&app, "/translations", create_request.to_string().into())
            .await?;

        let text_content: TextContent = serde_json::from_value(response)?;

        // Try to get non-existent translation
        let (status, response, _) = admin_session
            .get(
                &app,
                &format!("/translations/{}/nonexistent", text_content.id),
            )
            .await?;

        assert_eq!(status, StatusCode::NOT_FOUND);

        Ok(())
    }

    #[sqlx::test]
    async fn test_update_invalid_text_content(pool: sqlx::PgPool) -> Result<(), Box<dyn Error>> {
        let state = test_state().db(pool).call()?;
        let app = setup_server(Arc::new(state)).await?;

        let mut admin_session = UserSession::new_admin();
        admin_session.signup(&app).await?;

        let fake_uuid = uuid::Uuid::new_v4();
        let update_request = json!({
            "primary_locale": "es"
        });

        let (status, response, _) = admin_session
            .put(
                &app,
                &format!("/translations/{}", fake_uuid),
                update_request.to_string().into(),
            )
            .await?;

        println!("{response:#?}");

        assert_eq!(status, StatusCode::NOT_FOUND);

        Ok(())
    }

    #[sqlx::test]
    async fn test_empty_update_request(pool: sqlx::PgPool) -> Result<(), Box<dyn Error>> {
        let state = test_state().db(pool).call()?;
        let app = setup_server(Arc::new(state)).await?;

        let mut admin_session = UserSession::new_admin();
        admin_session.signup(&app).await?;

        // Create TextContent
        let create_request = json!({
            "primary_locale": "en",
            "format": "plain"
        });

        let (status, response, _) = admin_session
            .post(&app, "/translations", create_request.to_string().into())
            .await?;

        let text_content: TextContent = serde_json::from_value(response)?;

        // Try to update with empty object
        let empty_update = json!({});

        let (status, response, _) = admin_session
            .put(
                &app,
                &format!("/translations/{}", text_content.id),
                empty_update.to_string().into(),
            )
            .await?;

        assert_eq!(status, StatusCode::UNPROCESSABLE_ENTITY);

        Ok(())
    }
}
