use std::collections::{HashMap, HashSet};
use std::str::FromStr;
use std::{fmt, sync::Arc};

use crate::{
    error::ComhairleError, models::SqlxResultExt, translation_service::TranslationService,
};
use async_trait::async_trait;
use chrono::{DateTime, Utc};
use schemars::JsonSchema;
use sea_query::{Alias, Expr, Func, JoinType, PostgresQueryBuilder, Query, enum_def};
use sea_query_binder::SqlxBinder;
use serde::{Deserialize, Serialize};
use sqlx::{PgPool, prelude::FromRow, query_as_with};
use tracing::instrument;
use uuid::Uuid;

/// A type-safe wrapper around Uuid for referencing text content.
///
/// This wrapper provides type safety when referencing TextContent records from other models.
/// It ensures that only text content IDs are used where translatable content is expected,
/// preventing accidental confusion with other UUID fields.
///
/// # Examples
///
/// ```rust
/// use uuid::Uuid;
/// use comhairle::models::translations::TextContentId;
///
/// // Create from a UUID
/// let uuid = Uuid::new_v4();
/// let content_id = TextContentId::from(uuid);
///
/// // Convert back to UUID when needed
/// let uuid_back: Uuid = content_id.into();
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema)]
#[serde(transparent)]
pub struct TextContentId(pub Uuid);

impl TextContentId {
    /// Creates a new TextContentId with a random UUID.
    ///
    /// # Returns
    ///
    /// A new TextContentId with a randomly generated UUID.
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    /// Creates a TextContentId from a UUID.
    ///
    /// # Arguments
    ///
    /// * `uuid` - The UUID to wrap
    ///
    /// # Returns
    ///
    /// A new TextContentId wrapping the provided UUID.
    pub fn from_uuid(uuid: Uuid) -> Self {
        Self(uuid)
    }

    /// Returns the inner UUID value.
    ///
    /// # Returns
    ///
    /// The UUID wrapped by this TextContentId.
    pub fn as_uuid(&self) -> &Uuid {
        &self.0
    }

    /// Consumes the TextContentId and returns the inner UUID.
    ///
    /// # Returns
    ///
    /// The UUID that was wrapped by this TextContentId.
    pub fn into_uuid(self) -> Uuid {
        self.0
    }
}

impl Default for TextContentId {
    fn default() -> Self {
        Self::new()
    }
}

impl From<Uuid> for TextContentId {
    fn from(uuid: Uuid) -> Self {
        Self(uuid)
    }
}

impl From<TextContentId> for Uuid {
    fn from(content_id: TextContentId) -> Self {
        content_id.0
    }
}

impl From<TextContentId> for sea_query::Value {
    fn from(val: TextContentId) -> Self {
        val.0.into()
    }
}

impl From<&TextContentId> for sea_query::Value {
    fn from(val: &TextContentId) -> Self {
        val.0.into()
    }
}

impl fmt::Display for TextContentId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl FromStr for TextContentId {
    type Err = uuid::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(Self(Uuid::from_str(s)?))
    }
}

impl sqlx::Type<sqlx::Postgres> for TextContentId {
    fn type_info() -> sqlx::postgres::PgTypeInfo {
        <Uuid as sqlx::Type<sqlx::Postgres>>::type_info()
    }
}

impl<'r> sqlx::Decode<'r, sqlx::Postgres> for TextContentId {
    fn decode(
        value: sqlx::postgres::PgValueRef<'r>,
    ) -> Result<Self, Box<dyn std::error::Error + 'static + Send + Sync>> {
        let uuid = <Uuid as sqlx::Decode<sqlx::Postgres>>::decode(value)?;
        Ok(Self(uuid))
    }
}

impl<'q> sqlx::Encode<'q, sqlx::Postgres> for TextContentId {
    fn encode_by_ref(
        &self,
        buf: &mut sqlx::postgres::PgArgumentBuffer,
    ) -> Result<sqlx::encode::IsNull, Box<dyn std::error::Error + Send + Sync + 'static>> {
        <Uuid as sqlx::Encode<sqlx::Postgres>>::encode_by_ref(&self.0, buf)
    }
}

// ======================================
//
// Translations in JSONB columns
//
// Traits and helper functions for resolving translations in nested JSONB columns.
//
// ======================================

/// Implemented by types that may contain [`TextContentId`] references,
/// allowing every id nested within a value to be gathered into a single
/// batch before hitting the database.
///
/// This is the read-side counterpart to [`ResolveTranslations`]: before a
/// value can be resolved to its localized text, every [`TextContentId`] it
/// contains — however deeply nested inside structs, enums, `Vec`s, or
/// `Option`s — needs to be collected so [`resolve_translations`] can fetch
/// them all in one query, rather than one query per id.
///
/// Implemented directly for [`TextContentId`] (the base case, which inserts
/// itself into the output set), with blanket implementations for
/// `Option<T>` and `Vec<T>` so composite types automatically support
/// collection through those wrappers. Structs and enums generated by
/// `#[derive(Translatable)]` implement this by recursing into each
/// `#[translatable]` field.
///
/// Fields not marked `#[translatable]` are not visited, since they cannot
/// contain [`TextContentId`]s that need resolving.
pub trait CollectTextContentIds {
    /// Walks `self`, inserting every [`TextContentId`] found (at any depth)
    /// into `out`.
    ///
    /// # Arguments
    ///
    /// * `out` - Accumulator set that ids are inserted into. Typically
    ///   shared across many values (e.g. every row in a response) so a
    ///   single deduplicated set can be passed to [`resolve_translations`].
    fn collect_text_content_ids(&self, out: &mut HashSet<TextContentId>);
}

/// Implemented by types that contain [`TextContentId`] references and can
/// be converted into a "resolved" mirror type with those references
/// replaced by their localized `String` content.
///
/// Implemented directly for [`TextContentId`] (the base case, which looks
/// itself up in `map`), with blanket implementations for `Option<T>` and
/// `Vec<T>` so composite types resolve automatically through those
/// wrappers. Structs and enums generated by `#[derive(Translatable)]`
/// implement this by recursing into each `#[translatable]` field and
/// passing non-translatable fields through unchanged.
///
/// Resolution is intentionally infallible: a [`TextContentId`] missing from
/// `map` (see [`resolve_translations`] for when this can happen) resolves
/// to an empty string rather than propagating an error, so a single missing
/// translation can't fail an entire response.
pub trait ResolveTranslations {
    /// The resolved mirror of `Self`, with every [`TextContentId`] replaced
    /// by its resolved `String`. For [`TextContentId`] itself this is
    /// `String`; for a derived struct/enum, this is its generated
    /// `*Resolved` counterpart; for `Option<T>`/`Vec<T>`, this is
    /// `Option<T::Resolved>`/`Vec<T::Resolved>`.
    type Resolved;

    /// Consumes `self`, replacing every contained [`TextContentId`] with
    /// its resolved text from `map`.
    ///
    /// # Arguments
    ///
    /// * `map` - Pre-fetched translations, as returned by
    ///   [`resolve_translations`]. Must have been built from a superset of
    ///   the ids [`CollectTextContentIds::collect_text_content_ids`] would
    ///   gather from `self`, or missing ids can silently resolve to an
    ///   empty string.
    fn resolve(self, map: &HashMap<TextContentId, String>) -> Self::Resolved;
}

/// Implemented by types that represent "raw" setup input which needs to be
/// persisted as translatable text, converting them into their "built" form
/// backed by a [`TextContentId`].
///
/// This is the write-side counterpart to `ResolveTranslations`: where
/// resolving turns a [`TextContentId`] into a `String` for display, building
/// turns a `String` (from setup/creation input) into a [`TextContentId`] by
/// inserting a new `text_content`/`text_translation` row pair.
#[async_trait]
pub trait BuildTextTranslation {
    /// The built form of `Self`. For `String` this is [`TextContentId`];
    /// for `Option<T>` this is `Option<T::Built>`.
    type Built;

    /// Persists `self` as translatable text and returns its built form.
    ///
    /// # Errors
    ///
    /// Returns [`ComhairleError`] if the underlying insert fails.
    async fn build_text_translation(
        self,
        db: &PgPool,
        locale: &str,
        format: TextFormat,
    ) -> Result<Self::Built, ComhairleError>;
}

#[async_trait]
impl BuildTextTranslation for String {
    type Built = TextContentId;

    async fn build_text_translation(
        self,
        db: &PgPool,
        locale: &str,
        format: TextFormat,
    ) -> Result<Self::Built, ComhairleError> {
        let translation = new_translation(db, locale, &self, format).await?;
        Ok(translation.id)
    }
}

#[async_trait]
impl<T: BuildTextTranslation + Send> BuildTextTranslation for Option<T> {
    type Built = Option<T::Built>;

    async fn build_text_translation(
        self,
        db: &PgPool,
        locale: &str,
        format: TextFormat,
    ) -> Result<Self::Built, ComhairleError> {
        match self {
            Some(v) => Ok(Some(v.build_text_translation(db, locale, format).await?)),
            None => Ok(None),
        }
    }
}

/// A path to a specific location within a JSON value, built incrementally
/// during a tree walk and rendered in [RFC 6901](https://www.rfc-editor.org/info/rfc6901/)
/// JSON Pointer syntax (e.g. `/questions/0/text`).
///
/// Used by [`CollectTextContentIdsWithPath`] to record *where* in a
/// serialized JSON structure each [`TextContentId`] was found, so an admin
/// UI can look up and edit the translation for a specific nested field
/// without needing to know the shape of the JSON in advance.
pub struct JsonPointer {
    pub segments: Vec<PathSegment>,
}

/// A single step in a [`JsonPointer`] — either a named object key or an
/// array index.
pub enum PathSegment {
    /// An object key, e.g. the `text` in `.text`. Must match the field's
    /// *serialized* (post-serde-rename) name, or the resulting pointer
    /// won't resolve against the real JSON.
    Field(&'static str),
    /// An array index, e.g. the `0` in `[0]`.
    Index(usize),
}

impl JsonPointer {
    /// Appends a field/object-key segment. Pair with [`Self::pop`] when
    /// leaving that field during a recursive walk.
    pub fn push_field(&mut self, field: &'static str) {
        self.segments.push(PathSegment::Field(field))
    }

    /// Appends an array-index segment. Pair with [`Self::pop`] when leaving
    /// that element during a recursive walk.
    pub fn push_index(&mut self, index: usize) {
        self.segments.push(PathSegment::Index(index))
    }

    /// Removes the last segment, returning the pointer to its state before
    /// the matching `push_field`/`push_index` call. Used to backtrack after
    /// recursing into a field or array element, so the same `JsonPointer`
    /// can be reused across sibling fields without allocating a new one.
    pub fn pop(&mut self) {
        self.segments.pop();
    }
}

impl std::fmt::Display for PathSegment {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PathSegment::Field(field) => {
                write!(f, "{}", field.replace('~', "~0").replace('/', "~1"))
            }
            PathSegment::Index(index) => write!(f, "{}", index),
        }
    }
}

/// Renders this segment as it appears in an RFC 6901 pointer, escaping
/// `~` and `/` in field names (`~0` and `~1` respectively) since those
/// characters are structurally significant in the pointer syntax.
impl std::fmt::Display for JsonPointer {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut pointer = String::new();
        for segment in &self.segments {
            pointer.push_str(&format!("/{}", segment));
        }
        write!(f, "{}", pointer)
    }
}

/// Implemented by types that may contain [`TextContentId`] references,
/// recording the [`JsonPointer`] path to each one alongside its id.
///
/// This is the admin-facing counterpart to [`CollectTextContentIds`]: where
/// that trait gathers ids into a flat, deduplicated `HashSet` for batch
/// resolution to display text, this trait preserves *where* each id sits
/// within the JSON structure, so an admin UI can present and edit the
/// translation for a specific nested field (e.g. `questions/0/text`)
/// without needing prior knowledge of the JSON's shape.
///
/// Implemented directly for [`TextContentId`] (the base case, which records
/// the current pointer against itself), with blanket implementations for
/// `Option<T>` and `Vec<T>` that push an index segment per element. Structs
/// and enums generated by `#[derive(TranslatableJson)]` implement this by
/// pushing a field (or, for tagged enum variants, a variant/content)
/// segment before recursing into each `#[translatable]` field, then popping
/// it afterwards — so the pointer reflects the field's actual serialized
/// JSON position, respecting `serde` renames and enum tagging mode.
///
/// Unlike [`CollectTextContentIds`], results are collected into a `Vec`
/// rather than a `HashSet`: the same [`TextContentId`] may legitimately
/// appear at multiple distinct paths (e.g. two questions sharing a label),
/// and each occurrence needs its own path recorded separately.
pub trait CollectTextContentIdsWithPath {
    fn collect_text_content_ids_with_path(
        &self,
        pointer: &mut JsonPointer,
        out: &mut Vec<(String, TextContentId)>,
    );
}

// ======================================
//
// Implementations for [`TextContentId`]
//
// ======================================

impl CollectTextContentIds for TextContentId {
    fn collect_text_content_ids(&self, out: &mut HashSet<TextContentId>) {
        out.insert(*self);
    }
}

impl<T: CollectTextContentIds> CollectTextContentIds for Option<T> {
    fn collect_text_content_ids(&self, out: &mut HashSet<TextContentId>) {
        if let Some(v) = self {
            v.collect_text_content_ids(out);
        }
    }
}

impl<T: CollectTextContentIds> CollectTextContentIds for Vec<T> {
    fn collect_text_content_ids(&self, out: &mut HashSet<TextContentId>) {
        for item in self {
            item.collect_text_content_ids(out);
        }
    }
}

impl ResolveTranslations for TextContentId {
    type Resolved = String;

    fn resolve(self, map: &HashMap<TextContentId, String>) -> Self::Resolved {
        map.get(&self).cloned().unwrap_or_default()
    }
}

impl<T: ResolveTranslations> ResolveTranslations for Option<T> {
    type Resolved = Option<T::Resolved>;

    fn resolve(self, map: &HashMap<TextContentId, String>) -> Self::Resolved {
        self.map(|v| v.resolve(map))
    }
}

impl<T: ResolveTranslations> ResolveTranslations for Vec<T> {
    type Resolved = Vec<T::Resolved>;

    fn resolve(self, map: &HashMap<TextContentId, String>) -> Self::Resolved {
        self.into_iter().map(|v| v.resolve(map)).collect()
    }
}

impl CollectTextContentIdsWithPath for TextContentId {
    fn collect_text_content_ids_with_path(
        &self,
        pointer: &mut JsonPointer,
        out: &mut Vec<(String, TextContentId)>,
    ) {
        out.push((pointer.to_string(), *self))
    }
}

impl<T: CollectTextContentIdsWithPath> CollectTextContentIdsWithPath for Option<T> {
    fn collect_text_content_ids_with_path(
        &self,
        pointer: &mut JsonPointer,
        out: &mut Vec<(String, TextContentId)>,
    ) {
        if let Some(value) = self {
            value.collect_text_content_ids_with_path(pointer, out);
        }
    }
}

impl<T: CollectTextContentIdsWithPath> CollectTextContentIdsWithPath for Vec<T> {
    fn collect_text_content_ids_with_path(
        &self,
        pointer: &mut JsonPointer,
        out: &mut Vec<(String, TextContentId)>,
    ) {
        for (index, item) in self.iter().enumerate() {
            pointer.push_index(index);
            item.collect_text_content_ids_with_path(pointer, out);
            pointer.pop();
        }
    }
}

/// Resolves a batch of [`TextContentId`]s to their localized text content.
///
/// For each id, looks up the translation matching `locale`. If no translation
/// exists for that locale, falls back to the `text_content` row's
/// `primary_locale` translation instead — mirroring the fallback behavior of
/// [`TextContentId::query_to_localisation`] used for flat table columns.
///
/// # Arguments
///
/// * `db` - Database connection pool.
/// * `ids` - The set of content ids to resolve. Typically gathered via
///   [`CollectTextContentIds::collect_text_content_ids`] across every
///   translatable field/row in a response, then deduplicated, so that a
///   single query resolves all translations needed for that response.
/// * `locale` - The requested locale (e.g. `"fr"`) to resolve text into.
///
/// # Returns
///
/// A map from each resolvable [`TextContentId`] to its resolved text.
///
/// Ids that have neither a `locale` translation nor a `primary_locale`
/// fallback translation (e.g. a `text_content` row with no associated
/// `text_translation` rows at all — normally a data integrity issue) are
/// silently omitted from the returned map. Callers resolving via
/// [`ResolveTranslations::resolve`] will fall back to an empty string for
/// any id missing from the map; callers needing to detect this case
/// explicitly should diff the returned map's keys against `ids`.
///
/// Ids in `ids` that don't correspond to any `text_content` row at all are
/// also simply absent from the result, rather than causing an error.
///
/// # Errors
///
/// Returns [`ComhairleError`] if the query fails to execute.
pub async fn resolve_translations(
    db: &PgPool,
    ids: &[TextContentId],
    locale: &str,
) -> Result<HashMap<TextContentId, String>, ComhairleError> {
    let tt = Alias::new("tt");
    let tt_primary = Alias::new("tt_primary");

    let (sql, values) = Query::select()
        .column((TextContentIden::Table, TextContentIden::Id))
        .expr_as(
            Func::coalesce([
                Expr::col((tt.clone(), TextTranslationIden::Content)).into(),
                Expr::col((tt_primary.clone(), TextTranslationIden::Content)).into(),
            ]),
            Alias::new("content"),
        )
        .from(TextContentIden::Table)
        .join_as(
            JoinType::LeftJoin,
            TextTranslationIden::Table,
            tt.clone(),
            Expr::col((tt.clone(), TextTranslationIden::ContentId))
                .equals((TextContentIden::Table, TextContentIden::Id))
                .and(Expr::col((tt.clone(), TextTranslationIden::Locale)).eq(locale)),
        )
        .join_as(
            JoinType::LeftJoin,
            TextTranslationIden::Table,
            tt_primary.clone(),
            Expr::col((tt_primary.clone(), TextTranslationIden::ContentId))
                .equals((TextContentIden::Table, TextContentIden::Id))
                .and(
                    Expr::col((tt_primary.clone(), TextTranslationIden::Locale))
                        .equals((TextContentIden::Table, TextContentIden::PrimaryLocale)),
                ),
        )
        .and_where(
            Expr::col((TextContentIden::Table, TextContentIden::Id))
                .is_in(ids.iter().map(|id| id.into_uuid())),
        )
        .build_sqlx(PostgresQueryBuilder);

    let rows: Vec<(Uuid, Option<String>)> = query_as_with(&sql, values).fetch_all(db).await?;

    Ok(rows
        .into_iter()
        .filter_map(|(id, content)| content.map(|c| (id.into(), c)))
        .collect())
}

/// Represents the format of text content that can be stored in the system.
///
/// This enum defines the supported text formats for content storage and rendering.
/// Each format determines how the content should be processed and displayed.
#[derive(PartialEq, Debug, Clone, Copy, Serialize, Deserialize, JsonSchema, sqlx::Type)]
#[sqlx(type_name = "TEXT")]
#[serde(rename_all = "camelCase")]
pub enum TextFormat {
    /// Plain text format - no special formatting or markup
    #[sqlx(rename = "plain")]
    Plain,
    /// Markdown format - supports Markdown syntax for formatting
    #[sqlx(rename = "markdown")]
    Markdown,
    /// Rich text format - supports advanced formatting and styling
    #[sqlx(rename = "rich")]
    Rich,
}

impl From<TextFormat> for sea_query::Value {
    fn from(val: TextFormat) -> Self {
        sea_query::Value::String(Some(Box::new(val.to_string())))
    }
}

impl fmt::Display for TextFormat {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let value = match self {
            TextFormat::Plain => "plain",
            TextFormat::Markdown => "markdown",
            TextFormat::Rich => "rich",
        };
        write!(f, "{}", value)
    }
}

/// Represents text content that can be translated into multiple languages.
///
/// TextContent serves as the main container for content that needs to be available
/// in multiple locales. It defines the primary locale and format.
/// Individual translations are stored separately in TextTranslation records that reference this content.
#[derive(Serialize, Deserialize, JsonSchema, FromRow, Debug, PartialEq, Clone)]
#[enum_def(table_name = "text_content")]
pub struct TextContent {
    /// Unique identifier for this text content
    pub id: TextContentId,
    /// The primary locale/language code for this content (e.g., "en", "es", "fr")
    pub primary_locale: String,
    /// The format of the text content (plain, markdown, or rich)
    pub format: TextFormat,
    /// Timestamp when this content was created
    pub created_at: DateTime<Utc>,
    /// Timestamp when this content was last updated
    pub updated_at: DateTime<Utc>,
}

/// Represents a translation of text content in a specific locale.
///
/// TextTranslation stores the actual translated content for a specific language.
/// Each translation references a TextContent record and provides the translated
/// text in the specified locale. It also tracks whether the translation was
/// AI-generated and if it requires human validation.
#[derive(Serialize, Deserialize, JsonSchema, FromRow, Debug, PartialEq, Clone)]
#[enum_def(table_name = "text_translation")]
pub struct TextTranslation {
    /// Unique identifier for this translation
    pub id: Uuid,
    /// Reference to the TextContent this translation belongs to
    pub content_id: TextContentId,
    /// The locale/language code for this translation (e.g., "en", "es", "fr")
    pub locale: String,
    /// The actual translated text content
    pub content: String,
    /// Whether this translation was generated by AI
    pub ai_generated: bool,
    /// Whether this translation requires human validation
    pub requires_validation: bool,
    /// Timestamp when this translation was created
    pub created_at: DateTime<Utc>,
    /// Timestamp when this translation was last updated
    pub updated_at: DateTime<Utc>,
}

const TEXT_CONTENT_DEFAULT_COLUMNS: [TextContentIden; 5] = [
    TextContentIden::Id,
    TextContentIden::PrimaryLocale,
    TextContentIden::Format,
    TextContentIden::CreatedAt,
    TextContentIden::UpdatedAt,
];

const TEXT_TRANSLATION_DEFAULT_COLUMNS: [TextTranslationIden; 8] = [
    TextTranslationIden::Id,
    TextTranslationIden::ContentId,
    TextTranslationIden::Locale,
    TextTranslationIden::Content,
    TextTranslationIden::AiGenerated,
    TextTranslationIden::RequiresValidation,
    TextTranslationIden::CreatedAt,
    TextTranslationIden::UpdatedAt,
];

/// Data transfer object for creating new text content.
///
/// This struct contains all the required fields for creating a new TextContent
/// record in the database. The ID and timestamps will be automatically generated.
#[derive(Serialize, Deserialize, JsonSchema, Debug)]
pub struct CreateTextContent {
    /// The primary locale/language code for this content
    pub primary_locale: String,
    /// The format of the text content
    pub format: TextFormat,
}

impl CreateTextContent {
    /// Returns the database columns that will be inserted for this content.
    ///
    /// # Returns
    ///
    /// A vector of TextContentIden enum values representing the database columns.
    pub fn columns(&self) -> Vec<TextContentIden> {
        vec![TextContentIden::PrimaryLocale, TextContentIden::Format]
    }

    /// Returns the values to be inserted into the database columns.
    ///
    /// # Returns
    ///
    /// A vector of sea_query::SimpleExpr values corresponding to the columns.
    pub fn values(&self) -> Vec<sea_query::SimpleExpr> {
        vec![
            self.primary_locale.clone().into(),
            self.format.to_string().into(),
        ]
    }
}

/// Data transfer object for creating new text translations.
///
/// This struct contains all the required fields for creating a new TextTranslation
/// record in the database. The ID and timestamps will be automatically generated.
#[derive(Serialize, Deserialize, JsonSchema, Debug)]
pub struct CreateTextTranslation {
    /// Reference to the TextContent this translation belongs to
    pub content_id: TextContentId,
    /// The locale/language code for this translation
    pub locale: String,
    /// The actual translated text content
    pub content: String,
    /// Whether this translation was generated by AI (defaults to false)
    pub ai_generated: Option<bool>,
    /// Whether this translation requires human validation (defaults to false)
    pub requires_validation: Option<bool>,
}

impl CreateTextTranslation {
    /// Returns the database columns that will be inserted for this translation.
    ///
    /// # Returns
    ///
    /// A vector of TextTranslationIden enum values representing the database columns.
    pub fn columns(&self) -> Vec<TextTranslationIden> {
        vec![
            TextTranslationIden::ContentId,
            TextTranslationIden::Locale,
            TextTranslationIden::Content,
            TextTranslationIden::AiGenerated,
            TextTranslationIden::RequiresValidation,
        ]
    }

    /// Returns the values to be inserted into the database columns.
    ///
    /// # Returns
    ///
    /// A vector of sea_query::SimpleExpr values corresponding to the columns.
    /// Defaults ai_generated and requires_validation to false if not provided.
    pub fn values(&self) -> Vec<sea_query::SimpleExpr> {
        let ai_generated = self.ai_generated.unwrap_or(false);
        let requires_validation = self.requires_validation.unwrap_or(false);

        vec![
            self.content_id.into(),
            self.locale.clone().into(),
            self.content.clone().into(),
            ai_generated.into(),
            requires_validation.into(),
        ]
    }
}

/// Data transfer object for updating existing text content.
///
/// This struct contains optional fields that can be updated on a TextContent record.
/// Only the provided (Some) fields will be updated in the database.
#[derive(Serialize, Deserialize, JsonSchema, Debug)]
pub struct UpdateTextContent {
    /// The new primary locale/language code for this content
    pub primary_locale: Option<String>,
    /// The new format of the text content
    pub format: Option<TextFormat>,
}

impl UpdateTextContent {
    /// Converts the update struct to database column-value pairs.
    ///
    /// Only fields that are Some(..) will be included in the update.
    ///
    /// # Returns
    ///
    /// A vector of tuples containing the column identifier and the new value.
    pub fn to_values(&self) -> Vec<(TextContentIden, sea_query::SimpleExpr)> {
        let mut values = vec![];
        if let Some(value) = &self.primary_locale {
            values.push((TextContentIden::PrimaryLocale, value.into()));
        }
        if let Some(value) = &self.format {
            values.push((TextContentIden::Format, value.to_string().into()));
        }
        values
    }
}

/// Data transfer object for updating existing text translations.
///
/// This struct contains optional fields that can be updated on a TextTranslation record.
/// Only the provided (Some) fields will be updated in the database.
#[derive(Serialize, Deserialize, JsonSchema, Debug, Default)]
pub struct UpdateTextTranslation {
    /// The new locale/language code for this translation
    pub locale: Option<String>,
    /// The new translated text content
    pub content: Option<String>,
    /// Whether this translation was generated by AI
    pub ai_generated: Option<bool>,
    /// Whether this translation requires human validation
    pub requires_validation: Option<bool>,
}

impl UpdateTextTranslation {
    /// Converts the update struct to database column-value pairs.
    ///
    /// Only fields that are Some(..) will be included in the update.
    ///
    /// # Returns
    ///
    /// A vector of tuples containing the column identifier and the new value.
    pub fn to_values(&self) -> Vec<(TextTranslationIden, sea_query::SimpleExpr)> {
        let mut values = vec![];
        if let Some(value) = &self.locale {
            values.push((TextTranslationIden::Locale, value.into()));
        }
        if let Some(value) = &self.content {
            values.push((TextTranslationIden::Content, value.into()));
        }
        if let Some(value) = self.ai_generated {
            values.push((TextTranslationIden::AiGenerated, value.into()));
        }
        if let Some(value) = self.requires_validation {
            values.push((TextTranslationIden::RequiresValidation, value.into()));
        }
        values
    }
}

// TextContent CRUD operations

/// Creates a new text content record in the database.
///
/// # Arguments
///
/// * `db` - Database connection pool
/// * `text_content` - The text content data to create
///
/// # Returns
///
/// Returns a `Result` containing the created `TextContent` on success,
/// or a `ComhairleError` on failure.
///
/// # Errors
///
/// This function will return an error if:
/// * The database operation fails
#[instrument(err(Debug))]
pub async fn create_text_content(
    db: &PgPool,
    text_content: &CreateTextContent,
) -> Result<TextContent, ComhairleError> {
    let columns = text_content.columns();
    let values = text_content.values();

    let (sql, values) = Query::insert()
        .into_table(TextContentIden::Table)
        .columns(columns)
        .values(values)
        .unwrap()
        .returning(Query::returning().columns(TEXT_CONTENT_DEFAULT_COLUMNS))
        .build_sqlx(PostgresQueryBuilder);

    let text_content = sqlx::query_as_with::<_, TextContent, _>(&sql, values)
        .fetch_one(db)
        .await?;

    Ok(text_content)
}

/// Retrieves a text content record by its ID.
///
/// # Arguments
///
/// * `db` - Database connection pool
/// * `id` - The unique identifier of the text content to retrieve
///
/// # Returns
///
/// Returns a `Result` containing the `TextContent` if found,
/// or a `ComhairleError::ResourceNotFound` if not found.

#[instrument(err(Debug))]
pub async fn get_text_content_by_id(
    db: &PgPool,
    id: &TextContentId,
) -> Result<TextContent, ComhairleError> {
    let (sql, values) = Query::select()
        .columns(TEXT_CONTENT_DEFAULT_COLUMNS)
        .from(TextContentIden::Table)
        .and_where(Expr::col(TextContentIden::Id).eq(id.as_uuid().to_owned()))
        .build_sqlx(PostgresQueryBuilder);

    let text_content = sqlx::query_as_with::<_, TextContent, _>(&sql, values)
        .fetch_one(db)
        .await
        .resolve_db_err("Text Content")?;

    Ok(text_content)
}

/// Updates an existing text content record.
///
/// # Arguments
///
/// * `db` - Database connection pool
/// * `id` - The unique identifier of the text content to update
/// * `update` - The fields to update (only non-None fields will be updated)
///
/// # Returns
///
/// Returns a `Result` containing the updated `TextContent` on success,
/// or a `ComhairleError` on failure.
///
/// # Errors
///
/// This function will return an error if:
/// * No valid updates are provided (all fields are None)
/// * The text content with the given ID does not exist
/// * The database operation fails
#[instrument(err(Debug))]
pub async fn update_text_content(
    db: &PgPool,
    id: &TextContentId,
    update: &UpdateTextContent,
) -> Result<TextContent, ComhairleError> {
    let mut values = update.to_values();

    if values.is_empty() {
        return Err(ComhairleError::NoValidUpdates);
    }

    values.push((TextContentIden::CreatedAt, Utc::now().into()));

    let (sql, values) = Query::update()
        .table(TextContentIden::Table)
        .values(values)
        .and_where(Expr::col(TextContentIden::Id).eq(id.as_uuid().to_owned()))
        .returning(Query::returning().columns(TEXT_CONTENT_DEFAULT_COLUMNS))
        .build_sqlx(PostgresQueryBuilder);

    let text_content = sqlx::query_as_with::<_, TextContent, _>(&sql, values)
        .fetch_one(db)
        .await
        .resolve_db_err("Text Content")?;

    Ok(text_content)
}

/// Deletes a text content record from the database.
///
/// This will also cascade delete all associated translations due to
/// the foreign key constraint in the database.
///
/// # Arguments
///
/// * `db` - Database connection pool
/// * `id` - The unique identifier of the text content to delete
///
/// # Returns
///
/// Returns a `Result` containing the deleted `TextContent` on success,
/// or a `ComhairleError::ResourceNotFound` if the content doesn't exist.
#[instrument(err(Debug))]
pub async fn delete_text_content(
    db: &PgPool,
    id: &TextContentId,
) -> Result<TextContent, ComhairleError> {
    let (sql, values) = Query::delete()
        .from_table(TextContentIden::Table)
        .and_where(Expr::col(TextContentIden::Id).eq(id.as_uuid().to_owned()))
        .returning(Query::returning().columns(TEXT_CONTENT_DEFAULT_COLUMNS))
        .build_sqlx(PostgresQueryBuilder);

    let text_content = sqlx::query_as_with::<_, TextContent, _>(&sql, values)
        .fetch_one(db)
        .await
        .inspect_err(|e| println!("{e:#?}"))
        .resolve_db_err("Text Content")?;

    Ok(text_content)
}

// TextTranslation CRUD operations

/// Creates a new text translation record in the database.
///
/// # Arguments
///
/// * `db` - Database connection pool
/// * `text_translation` - The text translation data to create
///
/// # Returns
///
/// Returns a `Result` containing the created `TextTranslation` on success,
/// or a `ComhairleError` on failure.
///
/// # Errors
///
/// This function will return an error if:
/// * The database operation fails
/// * The content_id references a non-existent text content
/// * A translation for the same content_id and locale already exists
#[instrument(err(Debug))]
pub async fn create_text_translation(
    db: &PgPool,
    text_translation: &CreateTextTranslation,
) -> Result<TextTranslation, ComhairleError> {
    let columns = text_translation.columns();
    let values = text_translation.values();

    let (sql, values) = Query::insert()
        .into_table(TextTranslationIden::Table)
        .columns(columns)
        .values(values)
        .unwrap()
        .returning(Query::returning().columns(TEXT_TRANSLATION_DEFAULT_COLUMNS))
        .build_sqlx(PostgresQueryBuilder);

    let text_translation = sqlx::query_as_with::<_, TextTranslation, _>(&sql, values)
        .fetch_one(db)
        .await?;

    Ok(text_translation)
}

/// Retrieves a text translation record by its ID.
///
/// # Arguments
///
/// * `db` - Database connection pool
/// * `id` - The unique identifier of the text translation to retrieve
///
/// # Returns
///
/// Returns a `Result` containing the `TextTranslation` if found,
/// or a `ComhairleError::ResourceNotFound` if not found.
#[instrument(err(Debug))]
pub async fn get_text_translation_by_id(
    db: &PgPool,
    id: &Uuid,
) -> Result<TextTranslation, ComhairleError> {
    let (sql, values) = Query::select()
        .columns(TEXT_TRANSLATION_DEFAULT_COLUMNS)
        .from(TextTranslationIden::Table)
        .and_where(Expr::col(TextTranslationIden::Id).eq(id.to_owned()))
        .build_sqlx(PostgresQueryBuilder);

    let text_translation = sqlx::query_as_with::<_, TextTranslation, _>(&sql, values)
        .fetch_one(db)
        .await
        .resolve_db_err("Text Translation")?;

    Ok(text_translation)
}

/// Retrieves all text translation records for a specific text content.
///
/// # Arguments
///
/// * `db` - Database connection pool
/// * `content_id` - The unique identifier of the text content
///
/// # Returns
///
/// Returns a `Result` containing a vector of `TextTranslation` records,
/// or a `ComhairleError` on database failure. Returns an empty vector
/// if no translations are found for the content.
#[instrument(err(Debug))]
pub async fn get_text_translations_by_content_id(
    db: &PgPool,
    content_id: &TextContentId,
) -> Result<Vec<TextTranslation>, ComhairleError> {
    let (sql, values) = Query::select()
        .columns(TEXT_TRANSLATION_DEFAULT_COLUMNS)
        .from(TextTranslationIden::Table)
        .and_where(Expr::col(TextTranslationIden::ContentId).eq(content_id.as_uuid().to_owned()))
        .build_sqlx(PostgresQueryBuilder);

    let text_translations = sqlx::query_as_with::<_, TextTranslation, _>(&sql, values)
        .fetch_all(db)
        .await?;

    Ok(text_translations)
}

/// Retrieves a specific text translation by content ID and locale.
///
/// This is useful for finding a translation in a specific language
/// for a given piece of content.
///
/// # Arguments
///
/// * `db` - Database connection pool
/// * `content_id` - The unique identifier of the text content
/// * `locale` - The locale/language code of the desired translation
///
/// # Returns
///
/// Returns a `Result` containing the `TextTranslation` if found,
/// or a `ComhairleError::ResourceNotFound` if no translation exists
/// for the given content and locale combination.
#[instrument(err(Debug))]
pub async fn get_text_translation_by_content_and_locale(
    db: &PgPool,
    content_id: &TextContentId,
    locale: &str,
) -> Result<TextTranslation, ComhairleError> {
    let (sql, values) = Query::select()
        .columns(TEXT_TRANSLATION_DEFAULT_COLUMNS)
        .from(TextTranslationIden::Table)
        .and_where(Expr::col(TextTranslationIden::ContentId).eq(content_id.as_uuid().to_owned()))
        .and_where(Expr::col(TextTranslationIden::Locale).eq(locale))
        .build_sqlx(PostgresQueryBuilder);

    let text_translation = sqlx::query_as_with::<_, TextTranslation, _>(&sql, values)
        .fetch_one(db)
        .await
        .resolve_db_err("Text Translation")?;

    Ok(text_translation)
}

/// Updates an existing text translation record.
///
/// # Arguments
///
/// * `db` - Database connection pool
/// * `id` - The unique identifier of the text translation to update
/// * `update` - The fields to update (only non-None fields will be updated)
///
/// # Returns
///
/// Returns a `Result` containing the updated `TextTranslation` on success,
/// or a `ComhairleError` on failure.
///
/// # Errors
///
/// This function will return an error if:
/// * No valid updates are provided (all fields are None)
/// * The text translation with the given ID does not exist
/// * The database operation fails
/// * The updated locale would create a duplicate (content_id, locale) pair
#[instrument(err(Debug))]
pub async fn update_text_translation(
    db: &PgPool,
    id: &Uuid,
    update: &UpdateTextTranslation,
) -> Result<TextTranslation, ComhairleError> {
    let values = update.to_values();

    if values.is_empty() {
        return Err(ComhairleError::NoValidUpdates);
    }

    let (sql, values) = Query::update()
        .table(TextTranslationIden::Table)
        .values(values)
        .and_where(Expr::col(TextTranslationIden::Id).eq(id.to_owned()))
        .returning(Query::returning().columns(TEXT_TRANSLATION_DEFAULT_COLUMNS))
        .build_sqlx(PostgresQueryBuilder);

    let text_translation = sqlx::query_as_with::<_, TextTranslation, _>(&sql, values)
        .fetch_one(db)
        .await?;

    Ok(text_translation)
}

/// Deletes a text translation record from the database.
///
/// # Arguments
///
/// * `db` - Database connection pool
/// * `id` - The unique identifier of the text translation to delete
///
/// # Returns
///
/// Returns a `Result` containing the deleted `TextTranslation` on success,
/// or a `ComhairleError::ResourceNotFound` if the translation doesn't exist.
#[instrument(err(Debug))]
pub async fn delete_text_translation(
    db: &PgPool,
    id: &Uuid,
) -> Result<TextTranslation, ComhairleError> {
    let (sql, values) = Query::delete()
        .from_table(TextTranslationIden::Table)
        .and_where(Expr::col(TextTranslationIden::Id).eq(id.to_owned()))
        .returning(Query::returning().columns(TEXT_TRANSLATION_DEFAULT_COLUMNS))
        .build_sqlx(PostgresQueryBuilder);

    let text_translation = sqlx::query_as_with::<_, TextTranslation, _>(&sql, values)
        .fetch_one(db)
        .await
        .resolve_db_err("Text Translation")?;

    Ok(text_translation)
}

// Convenience functions for working with TextContentId

/// Creates a new text content and returns its ID for linking from other models.
///
/// This is a convenience function that creates text content and returns just the ID,
/// which can be used to link translatable content from other models like Conversation.
///
/// # Arguments
///
/// * `db` - Database connection pool
/// * `text_content` - The text content data to create
///
/// # Returns
///
/// Returns a `Result` containing the `TextContentId` of the created content,
/// or a `ComhairleError` on failure.
#[instrument(err(Debug))]
pub async fn create_text_content_and_get_id(
    db: &PgPool,
    text_content: &CreateTextContent,
) -> Result<TextContentId, ComhairleError> {
    let content = create_text_content(db, text_content).await?;
    Ok(content.id)
}

/// Retrieves the translation for a specific text content and locale, if it exists.
///
/// This is a convenience function that returns an Option instead of an error
/// when no translation is found, making it easier to handle optional translations.
///
/// # Arguments
///
/// * `db` - Database connection pool
/// * `content_id` - The unique identifier of the text content
/// * `locale` - The locale/language code of the desired translation
///
/// # Returns
///
/// Returns a `Result` containing `Some(TextTranslation)` if found,
/// `None` if no translation exists, or a `ComhairleError` on database failure.
#[instrument(err(Debug))]
pub async fn get_text_translation_optional(
    db: &PgPool,
    content_id: &TextContentId,
    locale: &str,
) -> Result<Option<TextTranslation>, ComhairleError> {
    match get_text_translation_by_content_and_locale(db, content_id, locale).await {
        Ok(translation) => Ok(Some(translation)),
        Err(ComhairleError::ResourceNotFound(_)) => Ok(None),
        Err(e) => Err(e),
    }
}

/// Translate all languages that exist for this
/// text content. Will use the primary_locale as the
/// base line and use the translator service to generate
/// all of the others
// TODO This can be improved, it currently looks up
// the text content for each translation. We can
// make this smoother
#[instrument(err(Debug), skip(translator))]
pub async fn auto_generate_all_translations(
    db: &PgPool,
    translator: &Arc<dyn TranslationService>,
    text_content_id: &TextContentId,
) -> Result<Vec<TextTranslation>, ComhairleError> {
    let text_content = get_text_content_by_id(db, text_content_id).await?;
    let translations = get_text_translations_by_content_id(db, text_content_id).await?;
    let mut result: Vec<TextTranslation> = vec![];
    for translation in translations.iter() {
        if translation.locale != text_content.primary_locale {
            let new_translation =
                auto_generate_translation(db, translator, text_content_id, &translation.locale)
                    .await?;
            result.push(new_translation);
        }
    }
    return Ok(result);
}

/// Update this translation using the primary local
/// as a reference
#[instrument(err(Debug), skip(translator))]
pub async fn auto_generate_translation(
    db: &PgPool,
    translator: &Arc<dyn TranslationService>,
    text_content_id: &TextContentId,
    locale: &str,
) -> Result<TextTranslation, ComhairleError> {
    let text_content = get_text_content_by_id(db, text_content_id).await?;

    println!("Trying to get translation with {text_content_id:#?} and {locale}");

    let translation =
        get_text_translation_by_content_and_locale(db, text_content_id, locale).await?;

    let reference_text = get_text_translation_by_content_and_locale(
        db,
        &text_content.id,
        &text_content.primary_locale,
    )
    .await?;

    let translated_text = translator
        .translate_from_to(
            &reference_text.content,
            &reference_text.locale,
            &translation.locale,
        )
        .await?;

    let updated_translation = update_text_translation(
        db,
        &translation.id,
        &UpdateTextTranslation {
            content: Some(translated_text),
            ai_generated: Some(true),
            requires_validation: Some(true),
            ..Default::default()
        },
    )
    .await?;
    Ok(updated_translation)
}

#[instrument(err(Debug))]
pub async fn new_translation(
    db: &PgPool,
    locale: &str,
    content: &str,
    format: TextFormat,
) -> Result<TextContent, ComhairleError> {
    let translation = create_text_content(
        db,
        &CreateTextContent {
            primary_locale: locale.to_owned(),
            format,
        },
    )
    .await?;

    create_text_translation(
        db,
        &CreateTextTranslation {
            content_id: translation.id,
            locale: locale.to_owned(),
            content: content.to_owned(),
            ai_generated: Some(false),
            requires_validation: Some(false),
        },
    )
    .await?;
    Ok(translation)
}

#[cfg(test)]
mod tests {
    use comhairle_macros::TranslatableJson;

    use super::*;

    use std::error::Error;

    struct TestWithTranslations {
        title: TextContentId,
        description: TextContentId,
    }

    struct LocalizedTestWithTranslations {
        title: String,
        description: String,
    }

    impl CollectTextContentIds for TestWithTranslations {
        fn collect_text_content_ids(&self, out: &mut HashSet<TextContentId>) {
            out.insert(self.title);
            out.insert(self.description);
        }
    }

    impl ResolveTranslations for TestWithTranslations {
        type Resolved = LocalizedTestWithTranslations;

        fn resolve(self, map: &HashMap<TextContentId, String>) -> Self::Resolved {
            LocalizedTestWithTranslations {
                title: map.get(&self.title).cloned().unwrap_or_default(),
                description: map.get(&self.description).cloned().unwrap_or_default(),
            }
        }
    }

    #[sqlx::test(migrator = "crate::SQLX_MIGRATOR")]
    async fn should_resolve_translations_for_arbitrary_list(
        pool: PgPool,
    ) -> Result<(), Box<dyn Error>> {
        let trans_a = new_translation(&pool, "en", "Test text a", TextFormat::Plain).await?;
        let trans_b = new_translation(&pool, "en", "Test text b", TextFormat::Plain).await?;
        let trans_c = new_translation(&pool, "en", "Test text c", TextFormat::Plain).await?;

        let ids = [trans_a.id, trans_b.id, trans_c.id];

        let result = resolve_translations(&pool, &ids, "en").await?;

        assert_eq!(
            result.get(&trans_a.id).unwrap(),
            "Test text a",
            "missing a translation"
        );
        assert_eq!(
            result.get(&trans_b.id).unwrap(),
            "Test text b",
            "missing b translation"
        );
        assert_eq!(
            result.get(&trans_c.id).unwrap(),
            "Test text c",
            "missing c translation"
        );

        Ok(())
    }

    #[sqlx::test(migrator = "crate::SQLX_MIGRATOR")]
    async fn should_resolve_translations_to_primary_locale_if_locale_translation_missing(
        pool: PgPool,
    ) -> Result<(), Box<dyn Error>> {
        let trans_a = new_translation(&pool, "en", "Test text a", TextFormat::Plain).await?;
        let trans_b = new_translation(&pool, "en", "Test text b", TextFormat::Plain).await?;
        let trans_c = new_translation(&pool, "en", "Test text c", TextFormat::Plain).await?;

        let ids = [trans_a.id, trans_b.id, trans_c.id];

        let result = resolve_translations(&pool, &ids, "fr").await?;

        assert_eq!(result.get(&trans_a.id).unwrap(), "Test text a");
        assert_eq!(result.get(&trans_b.id).unwrap(), "Test text b");
        assert_eq!(result.get(&trans_c.id).unwrap(), "Test text c");

        Ok(())
    }

    #[sqlx::test(migrator = "crate::SQLX_MIGRATOR")]
    async fn should_collect_text_content_ids_for_struct(
        pool: PgPool,
    ) -> Result<(), Box<dyn Error>> {
        let title = new_translation(&pool, "en", "Test title", TextFormat::Plain).await?;
        let description =
            new_translation(&pool, "en", "Test description", TextFormat::Plain).await?;

        let mut out: HashSet<TextContentId> = HashSet::new();
        let test_translation = TestWithTranslations {
            title: title.id,
            description: description.id,
        };

        test_translation.collect_text_content_ids(&mut out);

        assert!(out.contains(&test_translation.title), "missing title id");
        assert!(
            out.contains(&test_translation.description),
            "missing description id"
        );

        Ok(())
    }

    #[sqlx::test(migrator = "crate::SQLX_MIGRATOR")]
    async fn should_resolve_translations_for_struct_fields(
        pool: PgPool,
    ) -> Result<(), Box<dyn Error>> {
        let title = new_translation(&pool, "en", "Test title", TextFormat::Plain).await?;
        let description =
            new_translation(&pool, "en", "Test description", TextFormat::Plain).await?;

        let mut out: HashSet<TextContentId> = HashSet::new();
        let test_translation = TestWithTranslations {
            title: title.id,
            description: description.id,
        };

        test_translation.collect_text_content_ids(&mut out);

        let map = resolve_translations(&pool, &out.into_iter().collect::<Vec<_>>(), "en").await?;

        let resolved = test_translation.resolve(&map);

        assert_eq!(resolved.title, "Test title", "incorrect title");
        assert_eq!(
            resolved.description, "Test description",
            "incorrect descrition"
        );

        Ok(())
    }

    #[sqlx::test(migrator = "crate::SQLX_MIGRATOR")]
    async fn should_auto_implement_traits_to_resolve_translations(
        pool: PgPool,
    ) -> Result<(), Box<dyn Error>> {
        #[derive(TranslatableJson)]
        struct Root {
            #[translatable]
            title: TextContentId,
            #[translatable]
            nested_arr: Vec<Nested>,
        }

        #[derive(TranslatableJson)]
        struct Nested {
            #[translatable]
            text_field: TextContentId,
            other_field: String,
        }

        let root_title = new_translation(&pool, "en", "Root title", TextFormat::Plain).await?;
        let nested_a = new_translation(&pool, "en", "Nested a", TextFormat::Plain).await?;
        let nested_b = new_translation(&pool, "en", "Nested b", TextFormat::Plain).await?;

        let root = Root {
            title: root_title.id,
            nested_arr: vec![
                Nested {
                    text_field: nested_a.id,
                    other_field: "test a".to_string(),
                },
                Nested {
                    text_field: nested_b.id,
                    other_field: "test b".to_string(),
                },
            ],
        };

        let mut out: HashSet<TextContentId> = HashSet::new();
        root.collect_text_content_ids(&mut out);
        let map = resolve_translations(&pool, &out.into_iter().collect::<Vec<_>>(), "en").await?;
        let resolved = root.resolve(&map);

        assert_eq!(
            resolved.title,
            "Root title".to_string(),
            "incorrect root title"
        );
        assert_eq!(
            resolved.nested_arr[0].text_field, "Nested a",
            "incorrect nested a"
        );
        assert_eq!(
            resolved.nested_arr[1].text_field, "Nested b",
            "incorrect nested a"
        );

        Ok(())
    }

    #[sqlx::test(migrator = "crate::SQLX_MIGRATOR")]
    async fn should_collect_text_content_ids_with_json_pointer_paths_with_externally_tagged_enum(
        pool: PgPool,
    ) -> Result<(), Box<dyn Error>> {
        #[derive(serde::Serialize, TranslatableJson)]
        struct Root {
            #[translatable]
            title: TextContentId,
            #[translatable]
            nested_arr: Vec<Nested>,
        }

        #[derive(serde::Serialize, TranslatableJson)]
        struct Nested {
            #[translatable]
            text_field: TextContentId,
            other_field: String,
            #[translatable]
            external: ExternalTaggedEnum,
        }

        #[derive(serde::Serialize, TranslatableJson)]
        enum ExternalTaggedEnum {
            #[translatable]
            VarOne(InnerTrans),
            VarTwo(InnerRaw),
        }

        #[derive(serde::Serialize, TranslatableJson)]
        struct InnerTrans {
            #[translatable]
            value: TextContentId,
        }

        #[derive(
            serde::Serialize, PartialEq, Debug, serde::Deserialize, schemars::JsonSchema, Clone,
        )]
        struct InnerRaw {
            value: String,
        }

        let root_title = new_translation(&pool, "en", "Root title", TextFormat::Plain).await?;
        let nested_1_text =
            new_translation(&pool, "en", "Nested 1 text", TextFormat::Plain).await?;
        let nested_2_text =
            new_translation(&pool, "en", "Nested 2 text", TextFormat::Plain).await?;
        let nested_3_text =
            new_translation(&pool, "en", "Nested 3 text", TextFormat::Plain).await?;
        let ext_1_value = new_translation(&pool, "en", "Tagged 1 value", TextFormat::Plain).await?;
        let ext_2_value = new_translation(&pool, "en", "Tagged 2 value", TextFormat::Plain).await?;

        let root_json = Root {
            title: root_title.id,
            nested_arr: vec![
                Nested {
                    text_field: nested_1_text.id,
                    other_field: "test".to_string(),
                    external: ExternalTaggedEnum::VarOne(InnerTrans {
                        value: ext_1_value.id,
                    }),
                },
                Nested {
                    text_field: nested_2_text.id,
                    other_field: "test".to_string(),
                    external: ExternalTaggedEnum::VarTwo(InnerRaw {
                        value: "test".to_string(),
                    }),
                },
                Nested {
                    text_field: nested_3_text.id,
                    other_field: "test".to_string(),
                    external: ExternalTaggedEnum::VarOne(InnerTrans {
                        value: ext_2_value.id,
                    }),
                },
            ],
        };

        let mut pointer = JsonPointer { segments: vec![] };
        let mut path_id_pairs = Vec::new();
        root_json.collect_text_content_ids_with_path(&mut pointer, &mut path_id_pairs);

        assert_eq!(
            path_id_pairs.len(),
            6,
            "incorrect number of translations collected"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/title" && pair.1 == root_title.id),
            "missing root title tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/0/text_field" && pair.1 == nested_1_text.id),
            "missing nested_1 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/1/text_field" && pair.1 == nested_2_text.id),
            "missing nested_3 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/2/text_field" && pair.1 == nested_3_text.id),
            "missing nested_3 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/0/external/VarOne/value"
                    && pair.1 == ext_1_value.id),
            "missing ext 1 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/2/external/VarOne/value"
                    && pair.1 == ext_2_value.id),
            "missing ext 2 tc_id"
        );

        Ok(())
    }

    #[sqlx::test(migrator = "crate::SQLX_MIGRATOR")]
    async fn should_collect_text_content_ids_with_json_pointer_paths_with_internally_tagged_enum(
        pool: PgPool,
    ) -> Result<(), Box<dyn Error>> {
        #[derive(serde::Serialize, TranslatableJson)]
        struct Root {
            #[translatable]
            title: TextContentId,
            #[translatable]
            nested_arr: Vec<Nested>,
        }

        #[derive(serde::Serialize, TranslatableJson)]
        struct Nested {
            #[translatable]
            text_field: TextContentId,
            other_field: String,
            #[translatable]
            internal: InternalTaggedEnum,
        }

        #[derive(serde::Serialize, TranslatableJson)]
        #[serde(tag = "type")]
        enum InternalTaggedEnum {
            #[translatable]
            VarOne(InnerTrans),
            VarTwo(InnerRaw),
        }

        #[derive(serde::Serialize, TranslatableJson)]
        struct InnerTrans {
            #[translatable]
            value: TextContentId,
        }

        #[derive(
            serde::Serialize, PartialEq, Debug, serde::Deserialize, schemars::JsonSchema, Clone,
        )]
        struct InnerRaw {
            value: String,
        }

        let root_title = new_translation(&pool, "en", "Root title", TextFormat::Plain).await?;
        let nested_1_text =
            new_translation(&pool, "en", "Nested 1 text", TextFormat::Plain).await?;
        let nested_2_text =
            new_translation(&pool, "en", "Nested 2 text", TextFormat::Plain).await?;
        let nested_3_text =
            new_translation(&pool, "en", "Nested 3 text", TextFormat::Plain).await?;
        let int_1_value = new_translation(&pool, "en", "Tagged 1 value", TextFormat::Plain).await?;
        let int_2_value = new_translation(&pool, "en", "Tagged 2 value", TextFormat::Plain).await?;

        let root_json = Root {
            title: root_title.id,
            nested_arr: vec![
                Nested {
                    text_field: nested_1_text.id,
                    other_field: "test".to_string(),
                    internal: InternalTaggedEnum::VarOne(InnerTrans {
                        value: int_1_value.id,
                    }),
                },
                Nested {
                    text_field: nested_2_text.id,
                    other_field: "test".to_string(),
                    internal: InternalTaggedEnum::VarTwo(InnerRaw {
                        value: "test".to_string(),
                    }),
                },
                Nested {
                    text_field: nested_3_text.id,
                    other_field: "test".to_string(),
                    internal: InternalTaggedEnum::VarOne(InnerTrans {
                        value: int_2_value.id,
                    }),
                },
            ],
        };

        let mut pointer = JsonPointer { segments: vec![] };
        let mut path_id_pairs = Vec::new();
        root_json.collect_text_content_ids_with_path(&mut pointer, &mut path_id_pairs);

        assert_eq!(
            path_id_pairs.len(),
            6,
            "incorrect number of translations collected"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/title" && pair.1 == root_title.id),
            "missing root title tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/0/text_field" && pair.1 == nested_1_text.id),
            "missing nested_1 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/1/text_field" && pair.1 == nested_2_text.id),
            "missing nested_3 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/2/text_field" && pair.1 == nested_3_text.id),
            "missing nested_3 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/0/internal/value" && pair.1 == int_1_value.id),
            "missing int 1 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/2/internal/value" && pair.1 == int_2_value.id),
            "missing int 2 tc_id"
        );

        Ok(())
    }

    #[sqlx::test(migrator = "crate::SQLX_MIGRATOR")]
    async fn should_collect_text_content_ids_with_json_pointer_paths_with_adjacent_tagged_enum(
        pool: PgPool,
    ) -> Result<(), Box<dyn Error>> {
        #[derive(serde::Serialize, TranslatableJson)]
        struct Root {
            #[translatable]
            title: TextContentId,
            #[translatable]
            nested_arr: Vec<Nested>,
        }

        #[derive(serde::Serialize, TranslatableJson)]
        struct Nested {
            #[translatable]
            text_field: TextContentId,
            other_field: String,
            #[translatable]
            adjacent: AdjacentEnum,
        }

        #[derive(serde::Serialize, TranslatableJson)]
        #[serde(tag = "type", content = "body")]
        enum AdjacentEnum {
            #[translatable]
            VarOne(InnerTrans),
            VarTwo(InnerRaw),
        }

        #[derive(serde::Serialize, TranslatableJson)]
        struct InnerTrans {
            #[translatable]
            value: TextContentId,
        }

        #[derive(
            serde::Serialize, PartialEq, Debug, serde::Deserialize, schemars::JsonSchema, Clone,
        )]
        struct InnerRaw {
            value: String,
        }

        let root_title = new_translation(&pool, "en", "Root title", TextFormat::Plain).await?;
        let nested_1_text =
            new_translation(&pool, "en", "Nested 1 text", TextFormat::Plain).await?;
        let nested_2_text =
            new_translation(&pool, "en", "Nested 2 text", TextFormat::Plain).await?;
        let nested_3_text =
            new_translation(&pool, "en", "Nested 3 text", TextFormat::Plain).await?;
        let adj_1_value = new_translation(&pool, "en", "Tagged 1 value", TextFormat::Plain).await?;
        let adj_2_value = new_translation(&pool, "en", "Tagged 2 value", TextFormat::Plain).await?;

        let root_json = Root {
            title: root_title.id,
            nested_arr: vec![
                Nested {
                    text_field: nested_1_text.id,
                    other_field: "test".to_string(),
                    adjacent: AdjacentEnum::VarOne(InnerTrans {
                        value: adj_1_value.id,
                    }),
                },
                Nested {
                    text_field: nested_2_text.id,
                    other_field: "test".to_string(),
                    adjacent: AdjacentEnum::VarTwo(InnerRaw {
                        value: "test".to_string(),
                    }),
                },
                Nested {
                    text_field: nested_3_text.id,
                    other_field: "test".to_string(),
                    adjacent: AdjacentEnum::VarOne(InnerTrans {
                        value: adj_2_value.id,
                    }),
                },
            ],
        };

        let mut pointer = JsonPointer { segments: vec![] };
        let mut path_id_pairs = Vec::new();
        root_json.collect_text_content_ids_with_path(&mut pointer, &mut path_id_pairs);

        assert_eq!(
            path_id_pairs.len(),
            6,
            "incorrect number of translations collected"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/title" && pair.1 == root_title.id),
            "missing root title tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/0/text_field" && pair.1 == nested_1_text.id),
            "missing nested_1 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/1/text_field" && pair.1 == nested_2_text.id),
            "missing nested_3 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/2/text_field" && pair.1 == nested_3_text.id),
            "missing nested_3 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/0/adjacent/body/value"
                    && pair.1 == adj_1_value.id),
            "missing adjecent 1 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/2/adjacent/body/value"
                    && pair.1 == adj_2_value.id),
            "missing adjecent 2 tc_id"
        );

        Ok(())
    }

    #[sqlx::test(migrator = "crate::SQLX_MIGRATOR")]
    async fn should_collect_text_content_ids_with_json_pointer_paths_with_untagged_enum(
        pool: PgPool,
    ) -> Result<(), Box<dyn Error>> {
        #[derive(serde::Serialize, TranslatableJson)]
        struct Root {
            #[translatable]
            title: TextContentId,
            #[translatable]
            nested_arr: Vec<Nested>,
        }

        #[derive(serde::Serialize, TranslatableJson)]
        struct Nested {
            #[translatable]
            text_field: TextContentId,
            other_field: String,
            #[translatable]
            untagged: UntaggedEnum,
        }

        #[derive(serde::Serialize, TranslatableJson)]
        #[serde(untagged)]
        enum UntaggedEnum {
            #[translatable]
            VarOne(InnerTrans),
            VarTwo(InnerRaw),
        }

        #[derive(serde::Serialize, TranslatableJson)]
        struct InnerTrans {
            #[translatable]
            value: TextContentId,
        }

        #[derive(
            serde::Serialize, PartialEq, Debug, serde::Deserialize, schemars::JsonSchema, Clone,
        )]
        struct InnerRaw {
            value: String,
        }

        let root_title = new_translation(&pool, "en", "Root title", TextFormat::Plain).await?;
        let nested_1_text =
            new_translation(&pool, "en", "Nested 1 text", TextFormat::Plain).await?;
        let nested_2_text =
            new_translation(&pool, "en", "Nested 2 text", TextFormat::Plain).await?;
        let nested_3_text =
            new_translation(&pool, "en", "Nested 3 text", TextFormat::Plain).await?;
        let untagged_1_value =
            new_translation(&pool, "en", "Tagged 1 value", TextFormat::Plain).await?;
        let untagged_2_value =
            new_translation(&pool, "en", "Tagged 2 value", TextFormat::Plain).await?;

        let root_json = Root {
            title: root_title.id,
            nested_arr: vec![
                Nested {
                    text_field: nested_1_text.id,
                    other_field: "test".to_string(),
                    untagged: UntaggedEnum::VarOne(InnerTrans {
                        value: untagged_1_value.id,
                    }),
                },
                Nested {
                    text_field: nested_2_text.id,
                    other_field: "test".to_string(),
                    untagged: UntaggedEnum::VarTwo(InnerRaw {
                        value: "test".to_string(),
                    }),
                },
                Nested {
                    text_field: nested_3_text.id,
                    other_field: "test".to_string(),
                    untagged: UntaggedEnum::VarOne(InnerTrans {
                        value: untagged_2_value.id,
                    }),
                },
            ],
        };

        let mut pointer = JsonPointer { segments: vec![] };
        let mut path_id_pairs = Vec::new();
        root_json.collect_text_content_ids_with_path(&mut pointer, &mut path_id_pairs);

        assert_eq!(
            path_id_pairs.len(),
            6,
            "incorrect number of translations collected"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/title" && pair.1 == root_title.id),
            "missing root title tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/0/text_field" && pair.1 == nested_1_text.id),
            "missing nested_1 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/1/text_field" && pair.1 == nested_2_text.id),
            "missing nested_3 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/2/text_field" && pair.1 == nested_3_text.id),
            "missing nested_3 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/0/untagged/value"
                    && pair.1 == untagged_1_value.id),
            "missing untagged 1 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/2/untagged/value"
                    && pair.1 == untagged_2_value.id),
            "missing untagged 2 tc_id"
        );

        Ok(())
    }

    #[sqlx::test(migrator = "crate::SQLX_MIGRATOR")]
    async fn should_collect_text_content_ids_with_json_pointer_paths_with_camel_enum(
        pool: PgPool,
    ) -> Result<(), Box<dyn Error>> {
        #[derive(serde::Serialize, TranslatableJson)]
        struct Root {
            #[translatable]
            title: TextContentId,
            #[translatable]
            nested_arr: Vec<Nested>,
        }

        #[derive(serde::Serialize, TranslatableJson)]
        struct Nested {
            #[translatable]
            text_field: TextContentId,
            other_field: String,
            #[translatable]
            camel: CamelCaseEnum,
        }

        #[derive(serde::Serialize, TranslatableJson)]
        #[serde(rename_all = "snake_case")]
        enum CamelCaseEnum {
            #[translatable]
            VarOne(InnerTrans),
            VarTwo(InnerRaw),
        }

        #[derive(serde::Serialize, TranslatableJson)]
        struct InnerTrans {
            #[translatable]
            value: TextContentId,
        }

        #[derive(
            serde::Serialize, PartialEq, Debug, serde::Deserialize, schemars::JsonSchema, Clone,
        )]
        struct InnerRaw {
            value: String,
        }

        let root_title = new_translation(&pool, "en", "Root title", TextFormat::Plain).await?;
        let nested_1_text =
            new_translation(&pool, "en", "Nested 1 text", TextFormat::Plain).await?;
        let nested_2_text =
            new_translation(&pool, "en", "Nested 2 text", TextFormat::Plain).await?;
        let nested_3_text =
            new_translation(&pool, "en", "Nested 3 text", TextFormat::Plain).await?;
        let camel_1_value =
            new_translation(&pool, "en", "Tagged 1 value", TextFormat::Plain).await?;
        let camel_2_value =
            new_translation(&pool, "en", "Tagged 2 value", TextFormat::Plain).await?;

        let root_json = Root {
            title: root_title.id,
            nested_arr: vec![
                Nested {
                    text_field: nested_1_text.id,
                    other_field: "test".to_string(),
                    camel: CamelCaseEnum::VarOne(InnerTrans {
                        value: camel_1_value.id,
                    }),
                },
                Nested {
                    text_field: nested_2_text.id,
                    other_field: "test".to_string(),
                    camel: CamelCaseEnum::VarTwo(InnerRaw {
                        value: "test".to_string(),
                    }),
                },
                Nested {
                    text_field: nested_3_text.id,
                    other_field: "test".to_string(),
                    camel: CamelCaseEnum::VarOne(InnerTrans {
                        value: camel_2_value.id,
                    }),
                },
            ],
        };

        let mut pointer = JsonPointer { segments: vec![] };
        let mut path_id_pairs = Vec::new();
        root_json.collect_text_content_ids_with_path(&mut pointer, &mut path_id_pairs);

        assert_eq!(
            path_id_pairs.len(),
            6,
            "incorrect number of translations collected"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/title" && pair.1 == root_title.id),
            "missing root title tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/0/text_field" && pair.1 == nested_1_text.id),
            "missing nested_1 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/1/text_field" && pair.1 == nested_2_text.id),
            "missing nested_3 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/2/text_field" && pair.1 == nested_3_text.id),
            "missing nested_3 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/0/camel/var_one/value"
                    && pair.1 == camel_1_value.id),
            "missing camel 1 tc_id"
        );
        assert!(
            path_id_pairs
                .iter()
                .any(|pair| pair.0 == "/nested_arr/2/camel/var_one/value"
                    && pair.1 == camel_2_value.id),
            "missing camel 2 tc_id"
        );

        Ok(())
    }
}
