use chrono::{DateTime, Utc};
use schemars::JsonSchema;
use sea_query::{Expr, PostgresQueryBuilder, Query, enum_def};
use sea_query_binder::SqlxBinder;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sqlx::{PgPool, prelude::FromRow, query_as_with};
use tracing::instrument;
use uuid::Uuid;

use crate::{
    error::ComhairleError,
    models::pagination::{PageOptions, PaginatedResults},
};

/// A stored Polis conversation summary generated by the sensemaking worker.
/// `poll_data` is a copy of the data sent to the worker; `result` is the
/// `WikiPollReportResult` it produced (group descriptions, consensus and
/// disagreement descriptions). Both are stored as opaque JSON rather than
/// through `sensemakar_types`, which uses a different `schemars` major
/// version than the rest of the API and can't satisfy this crate's
/// `JsonSchema` bound.
#[derive(Serialize, Deserialize, FromRow, Clone, JsonSchema, Debug)]
#[enum_def(table_name = "wiki_poll_conversation_summary")]
pub struct WikiPollConversationSummary {
    pub id: Uuid,
    pub workflow_step_id: Uuid,
    pub job_id: Option<Uuid>,
    pub poll_data: Value,
    pub result: Value,
    pub created_at: DateTime<Utc>,
}

const DEFAULT_COLUMNS: [WikiPollConversationSummaryIden; 6] = [
    WikiPollConversationSummaryIden::Id,
    WikiPollConversationSummaryIden::WorkflowStepId,
    WikiPollConversationSummaryIden::JobId,
    WikiPollConversationSummaryIden::PollData,
    WikiPollConversationSummaryIden::Result,
    WikiPollConversationSummaryIden::CreatedAt,
];

#[derive(Debug)]
pub struct CreateWikiPollConversationSummary {
    pub workflow_step_id: Uuid,
    pub job_id: Option<Uuid>,
    pub poll_data: Value,
    pub result: Value,
}

#[instrument(err(Debug), skip(db))]
pub async fn create(
    db: &PgPool,
    create: &CreateWikiPollConversationSummary,
) -> Result<WikiPollConversationSummary, ComhairleError> {
    let (sql, values) = Query::insert()
        .into_table(WikiPollConversationSummaryIden::Table)
        .columns([
            WikiPollConversationSummaryIden::WorkflowStepId,
            WikiPollConversationSummaryIden::JobId,
            WikiPollConversationSummaryIden::PollData,
            WikiPollConversationSummaryIden::Result,
        ])
        .values([
            create.workflow_step_id.into(),
            create.job_id.into(),
            create.poll_data.clone().into(),
            create.result.clone().into(),
        ])?
        .returning(Query::returning().columns(DEFAULT_COLUMNS))
        .build_sqlx(PostgresQueryBuilder);

    let summary = query_as_with(&sql, values).fetch_one(db).await?;

    Ok(summary)
}

#[instrument(err(Debug), skip(db))]
pub async fn get_latest_by_workflow_step_id(
    db: &PgPool,
    workflow_step_id: &Uuid,
) -> Result<Option<WikiPollConversationSummary>, ComhairleError> {
    let (sql, values) = Query::select()
        .columns(DEFAULT_COLUMNS)
        .from(WikiPollConversationSummaryIden::Table)
        .and_where(Expr::col(WikiPollConversationSummaryIden::WorkflowStepId).eq(*workflow_step_id))
        .order_by(
            WikiPollConversationSummaryIden::CreatedAt,
            sea_query::Order::Desc,
        )
        .limit(1)
        .build_sqlx(PostgresQueryBuilder);

    let summary = query_as_with(&sql, values).fetch_optional(db).await?;

    Ok(summary)
}

#[instrument(err(Debug), skip(db))]
pub async fn list_by_workflow_step_id(
    db: &PgPool,
    workflow_step_id: &Uuid,
    page_options: PageOptions,
) -> Result<PaginatedResults<WikiPollConversationSummary>, ComhairleError> {
    let query = Query::select()
        .columns(DEFAULT_COLUMNS)
        .from(WikiPollConversationSummaryIden::Table)
        .and_where(Expr::col(WikiPollConversationSummaryIden::WorkflowStepId).eq(*workflow_step_id))
        .order_by(
            WikiPollConversationSummaryIden::CreatedAt,
            sea_query::Order::Desc,
        )
        .to_owned();

    let summaries = page_options.fetch_paginated_results(db, query).await?;

    Ok(summaries)
}

#[cfg(test)]
mod tests {
    use super::*;

    use std::error::Error;

    #[sqlx::test(migrator = "crate::SQLX_MIGRATOR")]
    async fn should_create_and_fetch_latest(pool: PgPool) -> Result<(), Box<dyn Error>> {
        use crate::models::model_test_helpers::setup_default_app_and_session;
        use crate::test_helpers::{extract, polis_tool_config};
        use serde_json::json;

        let (app, mut session) = setup_default_app_and_session(&pool).await?;

        let (_, conversation, _) = session.create_random_conversation(&app).await?;
        let conversation_id: String = extract("id", &conversation);

        let (_, workflow, _) = session
            .create_random_workflow(&app, &conversation_id)
            .await?;
        let workflow_id: String = extract("id", &workflow);

        let (_, workflow_step, _) = session
            .post(
                &app,
                &format!("/conversation/{conversation_id}/workflow/{workflow_id}/workflow_step"),
                json!({
                    "name": "Polis step",
                    "step_order": 1,
                    "activation_rule": "manual",
                    "description": "polis step",
                    "is_offline": false,
                    "required": true,
                    "tool_setup": polis_tool_config(),
                })
                .to_string()
                .into(),
            )
            .await?;
        let workflow_step_id = Uuid::parse_str(&extract::<String>("id", &workflow_step))?;

        let first = create(
            &pool,
            &CreateWikiPollConversationSummary {
                workflow_step_id,
                job_id: None,
                poll_data: json!({ "title": "t", "statements": [] }),
                result: json!({ "consensus_description": "first" }),
            },
        )
        .await?;
        assert_eq!(first.workflow_step_id, workflow_step_id);

        let second = create(
            &pool,
            &CreateWikiPollConversationSummary {
                workflow_step_id,
                job_id: None,
                poll_data: json!({ "title": "t", "statements": [] }),
                result: json!({ "consensus_description": "second" }),
            },
        )
        .await?;

        let latest = get_latest_by_workflow_step_id(&pool, &workflow_step_id)
            .await?
            .expect("a summary should exist");
        assert_eq!(latest.id, second.id, "latest should be the most recent one");

        let list =
            list_by_workflow_step_id(&pool, &workflow_step_id, PageOptions::default()).await?;
        assert_eq!(list.total, 2);
        assert_eq!(list.records[0].id, second.id);
        assert_eq!(list.records[1].id, first.id);

        Ok(())
    }
}
