use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, JsonSchema, Debug, Clone)]
pub struct QuestionChain {
    pub base_interaction: QuestionWithAnswer,
    pub follow_ups: Vec<QuestionWithAnswer>,
}

#[derive(Serialize, Deserialize, JsonSchema, Debug, Clone)]
pub struct QuestionWithAnswer {
    pub question: Question,
    pub answer: Answer,
}

#[derive(Serialize, Deserialize, JsonSchema, Debug, Clone)]
pub struct Question {
    /// The question being asked
    pub text: String,
    /// The reasion for asking this question
    pub asking_reasion: String,
    /// If the question was generated by AI or not
    pub ai_generated: bool,
}

#[derive(Serialize, Deserialize, JsonSchema, Debug, Clone)]
pub struct Answer {
    pub text: String,
}
