name: build-api-docker

on:
  workflow_dispatch:  # Allows manual triggering
    inputs:
      dry_run:
        description: When true, do not push images
        required: false
        default: false
        type: boolean
  workflow_call:  # Allows workflow to be called by other workflows
    inputs:
      dry_run:
        description: When true, do not push images
        required: false
        default: false
        type: boolean

jobs:
  build-and-push-release:
    if: startsWith(github.ref, 'refs/tags/v') && github.ref_type == 'tag'
    uses: ./.github/workflows/api-build-shared.yml
    with:
      tags: |
        crownshy/comhairle_api:${{ github.ref_name }}
        crownshy/comhairle_api:latest
      cache_from: |
        type=gha
        type=registry,ref=crownshy/comhairle_api:latest
      dry_run: ${{ inputs.dry_run || false }}
    secrets: inherit
      
  build-and-push-staging:
    if: github.ref == 'refs/heads/staging'
    uses: ./.github/workflows/api-build-shared.yml
    with:
      tags: |
        crownshy/comhairle_api:${{ github.sha }}
        crownshy/comhairle_api:staging
      cache_from: |
        type=gha
        type=registry,ref=crownshy/comhairle_api:staging
        type=registry,ref=crownshy/comhairle_api:latest
      dry_run: ${{ inputs.dry_run || false }}
    secrets: inherit
     
  build-and-push-demo-young-scot:
    if: github.ref == 'refs/heads/demo/young-scot'
    uses: ./.github/workflows/api-build-shared.yml
    with:
      tags: |
        crownshy/comhairle_api:${{ github.sha }}
      cache_from: |
        type=gha
        type=registry,ref=crownshy/comhairle_api:demo-young-scot
        type=registry,ref=crownshy/comhairle_api:latest
      dry_run: ${{ inputs.dry_run || false }}
    secrets: inherit
     

